### ISSUE TITLE
Introduce customization callback for `Scenario` instances

### ISSUE THREAD

**Issue by danstooamerican** [spring-projects/spring-modulith#165]
I am currently trying to write a simple test using the new Scenario-API. I want to test that a module creates a database record after an event is published. This is my test setup:

```
@Test
void database_record_is_created_after_event(Scenario scenario) {
    // ... left out for brevity
    SomeEvent event = new SomeEvent (payload);

    scenario.publish(event)
            .andWaitForStateChange(() -> myRepositoryBean.findById(expectedId), Optional::isPresent) // see sidenote
            .andVerify(myOptional-> {
                MyDatabaseRecord record = myOptional.orElseThrow();

                // assertions...
            });
}
```

This test fails even though I verified that the object is created and saved. I also tried to replace the repository bean with a service that has its own `@Transactional` annotation.

The following test case succeeds but defeats the purpose of calling `andWaitForStateChange(...)`.

```
@Test
void database_record_is_created_after_event(Scenario scenario) {
    // ... left out for brevity
    SomeEvent event = new SomeEvent (payload);

    scenario.publish(event)
            .andWaitForStateChange(() -> Optional.empty(), Optional::isEmpty) // trivial accept so I can call .andVerify(...)
            .andVerify(myOptional-> {
                MyDatabaseRecord record = myRepositoryBean.findById(expectedId);

                // assertions...
            });
}
```

Sidenote: In my first code example I am required to specify a condition in the  `andWaitForStateChange(...)` call. Otherwise, my supplier is only called once and not polled regularly. This seems odd to me because the documentation states that it should work by without a condition with `Optional<T>`.

**Comment by danstooamerican** [comment]
I figured out my problem. Awaitility creates a separate thread. Since my application relies on `ThreadLocal` variables for storing the current tenant context, the wrong database was queried. Thus, the condition was never met.

My current solution is to use the `customize(...)` method to configure a custom executor service that initializes the tenant context. Is it possible to simplify this? Right now I always need to remember to call `customize(...)` which is unfortunate. I would much rather have Modulith pick up my executor service automatically.

**Comment by odrotbohm** [comment]
In the regular execution of the production code, who's setting the value then? Wouldn't you rather invoke a codepath that sets that value, too, when defining the completion cause?

**Comment by danstooamerican** [comment]
In production code the tenant context is initialized whenever our REST API is called. The included JWT is used to identify the correct tenant. We configured a `TaskDecorator` to propagate the tenant context for methods annotated with `@Async`. The task decorator is passed to a custom `ThreadPoolTaskExecutor` bean that is picked up by Spring. Additionally, we created aspects that initialize the tenant context for event handlers.
So far this solution has served us well and doesn't play a big role when implementing new features.

In the case of testing, I would also like to keep the tenant context outside of the individual test methods as far as possible. I wrote a base class for our tests that initializes the tenant context in the `beforeEach` hook. In the case of Awaitility, I have to either configure the tenant context manually or set my custom `ExecutorService`. The latter has the advantage, that the tenant context initialization is encapsulated in a separate class.

If we could find a solution that eliminates the need for calling `customize(...)` in every scenario test, I would be very happy.

**Comment by odrotbohm** [comment]
That's very valuable information. Thanks for that. I'll consult @sbrannen on how we might be able to provide hooks to prepare the `Scenario` instance accordingly.

**Comment by odrotbohm** [comment]
I've put API in place in the form of a `ScenarioCustomizer`, which you'd implement and register your implementation as a JUnit extension (`@ExtendWith(…)`). Find more information in the snapshot documentation, and please let me know if that works for you.

**Comment by odrotbohm** [comment]
I've just consulted the Boot team and it looks like we should be able to apply the following default:

1. If a bean of type `ExecutorService` is defined in the `ApplicationContext` we forward that to Awaitility.
2. If a bean of type `ThreadPoolTaskExecutor` is defined, we forward the underlying `ThreadPoolExecutor`. This is the bean that Boot's scheduling auto-configuration creates.

I am wondering if that would forward the customizations you made to the scheduling infrastructure. Do you think you could try something like this with your project and see whether it works for you?

```java
private Function<ConditionFactory, ConditionFactory> defaultScenarioCustomizer(ApplicationContext context) {

  Supplier<ExecutorService> fallback = () -> {
    var executor = context.getBeanProvider(ThreadPoolTaskExecutor.class).getIfUnique();
    return executor == null ? null : executor.getThreadPoolExecutor();
  };

  ExecutorService executorService = context.getBeanProvider(ExecutorService.class).getIfUnique(fallback);

  return executorService != null ? it -> it.pollExecutorService(executorService) : Function.identity();
}
```

**Comment by odrotbohm** [comment]
Closing this as the fundamentals were already introduced in 0.6. I'll create a new ticket for the `ExecutorService` propagation.
