### ISSUE TITLE
`@ApplicationModuleTest` triggers event handlers outside the tested module

### ISSUE THREAD

**Issue by danstooamerican** [spring-projects/spring-modulith#166]
I have an integration test that tests the reaction of a module to outside events. I annotated my test class with `@ApplicationModuleTest` and wrote my test using the Scenario API.

```
scenario.publish(event)
                .andWaitForStateChange(() -> // ...)
                .andVerify(object-> {
                    // ...
                });
```

The test itself works fine but I noticed exceptions in my test logs which occur in event handlers from another module. I would expect that only event handlers inside the module under test are executed since I run the test in standalone mode. The Modulith logs also don't list the other module as included.

It might be worth noting that the event I publish in my test is usually published from the module which is wrongly included in the test execution.

I am using version `0.6.0-SNAPSHOT`.

**Comment by odrotbohm** [comment]
Any chance you provide a minimal reproducer? How are the mistakenly triggered event listeners declared and in which modules do they reside in?

**Comment by danstooamerican** [comment]
I am currently not able to reproduce the behavior in a minimal reproducer. So far everything works as expected. However, I am definitely observing event handlers from other modules getting triggered in my main project.

The package structure looks like this:
```
| - main
    | - basePackage
        | - module1
            | - featureA
                | - MyWronglyExecutedEventHandlerClass
        | - module2
             | - featureB
                 | - MyCorrectlyExecutedEventHandlerClass
| - test
    | - basePackage
        | - module2
             | - Module2IntegrationTest
```

I don't have the time to investigate this further as it is only a minor annoyance at the moment. I would be willing to set up a meeting so I can show the behavior live if this is something you are interested in.

**Comment by thomascaillier** [comment]
Hello ! 
I have a similar problem.

Here is a module architecture :
```
com.example.modulithdemo
- ModulithDemoApplication.java
- payment
-- PaymentService.java
- order
-- partner
--- package-info.java (@NamedInterface("order-partner"))
--- PartnerAppOrderService.java (has no dependency)
-- website
--- package-info.java (@NamedInterface("order-website"))
--- PartnerAppOrderService.java (has a dependency to PaymentService)
```

When I unit test the `order.partner` module with `@ApplicationModuleTest`, there is an application context error because the `PaymentService` bean could not be found. But it is not a dependency of `order.partner` module, only one of `order.website` module.

Here is the source : https://github.com/thomascaillier/modulith-demo

**Comment by odrotbohm** [comment]
This works as expected. The test case bootstraps the `order` module. That contains `website.WebsiteOrderService`, which in turn exposes a dependency to `PaymentService` in its constructor. There is no `order.partner` or `order.website` module. They are simply sub-packages within the `order` module. Your declaration of them as named interfaces does not change that.

**Comment by thomascaillier** [comment]
Okay, thanks for the explanation !
