### ISSUE TITLE
Event expected to arrive in integration test never arrives

### ISSUE THREAD

**Issue by splatter0** [spring-projects/spring-modulith#204]
I met a problem when i'm using spring-modulith-events in a project, example detailed as below:
https://github.com/xjianyu/spring-modulith-events-example/blob/main/src/test/java/com/example/order/OrderTests.java

**Comment by xjianyu** [comment]
create order then pay order, pay order cannot be executed
<img width="923" alt="image" src="https://github.com/spring-projects/spring-modulith/assets/19404942/13232b21-e63b-4713-acfa-d220618be5d3">

**Comment by xjianyu** [comment]
`@Transactional
    @TransactionalEventListener
    public void onOrderCreated(OrderCreated event) {
        log.info("order created {}", event.getId());
        orderPaidService.pay(event.getId());
    }`

change into

`@Transactional(propagation = Propagation.REQUIRES_NEW)
    @TransactionalEventListener
    public void onOrderCreated(OrderCreated event) {
        log.info("order created {}", event.getId());
        orderPaidService.pay(event.getId());
    }`

It will be ok, I don't know why

**Comment by odrotbohm** [comment]
As transactional event listeners are invoked during the transaction cleanup phase, marking them as `@Transactional` will not have the effect of actually running the method in a transactional way. Thus, and as you already have discovered, you will need to use `Propagation.REQUIRES_NEW`. This is one of the reasons `@ApplicationModuleListener` exists, as it sets up a transactional event listener with a new transaction.

I'll take this forward to the team to debate whether we can detect such a misconfiguration and report the problem to users in a reasonable way.

**Comment by odrotbohm** [comment]
I've filed https://github.com/spring-projects/spring-framework/issues/30679 to make sure Spring Framework already detects that misconfiguration on application startup.
