### ISSUE TITLE
andWaitForEventOfType tests fail without @SpringBootTest and @EnableScenarios annotations

### ISSUE THREAD

**Issue by yossisp** [spring-projects/spring-modulith#214]
Hi Spring Modulith team, first and foremost thank you for the amazing project!

I've been following [Defining Integration Test Scenarios](https://docs.spring.io/spring-modulith/docs/current/reference/html/#testing.scenarios) section from the official docs and wanted to add a test which uses `andWaitForEventOfType` to wait for another event. I forked the repo and added this test:
```java
@ApplicationModuleTest
@RequiredArgsConstructor
class WaitForEventOfTypeDoesntWorkTests {

    @Test
    void andWaitForEventOfTypeDoesntWork(Scenario scenario) {

        var order = new Order();

        /*
         * The test fails because @SpringBootTest and @EnableScenarios annotations are missing
         */
        scenario.publish(new OrderCompleted(order.getId()))
                .andWaitForEventOfType(InventoryUpdated.class)
                .toArrive();
    }
}
```
in `spring-modulith/spring-modulith-examples/spring-modulith-example-full/src/test/java/example/order/WaitForEventOfTypeDoesntWorkTests.java`. The test fails because `@SpringBootTest` and `@EnableScenarios` annotations need to applied to the class instead of `@ApplicationModuleTest`. I realized this after I came across `spring-modulith/spring-modulith-examples/spring-modulith-example-epr-jdbc/src/test/java/example/ApplicationIntegrationTests.java` test. When I added the same `andWaitForEventOfTypeDoesntWork` test in the `ApplicationIntegrationTests.java` it worked the only difference being those 2 annotations.

I'm seeking clarification on which annotations are needed for `andWaitForEventOfType` type of tests to work. FYI `@EnableScenarios` is not mentioned in the official docs.

This is the demo [repo](https://github.com/yossisp/spring-modulith/blob/WaitForEventOfType-doesnt-work-without-SpringBootTest/spring-modulith-examples/spring-modulith-example-full/src/test/java/example/order/WaitForEventOfTypeDoesntWorkTests.java) with the above failing test.

**Comment by odrotbohm** [comment]
The test seems to be invalid. It resides in the `example.order` package and thus *only* bootstraps the order module. The component that publishes the event you are waiting for lives in the `inventory` package, which is not part of the bootstrap. This means that this test correctly fails, as no one in the test context actually publishes the event you're waiting for.

**Comment by yossisp** [comment]
@odrotbohm Good catch! Added `@ApplicationModuleTest(mode = ApplicationModuleTest.BootstrapMode.ALL_DEPENDENCIES)` for `WaitForEventOfTypeDoesntWorkTests` class in the same [repo](https://github.com/yossisp/spring-modulith/blob/WaitForEventOfType-doesnt-work-without-SpringBootTest/spring-modulith-examples/spring-modulith-example-full/src/test/java/example/order/WaitForEventOfTypeDoesntWorkTests.java#L32) however still getting the same error:
```
org.awaitility.core.ConditionTimeoutException: org.springframework.modulith.test.Scenario$When$EventResult expected the predicate to return <true> but it returned <false> for input of <[]> within 10 seconds.
```
Does the test pass for you?

**Comment by odrotbohm** [comment]
No, because the assumption is still invalid 🙃: `ALL_DEPENDENCIES` means that all downstream dependencies of the module about to be bootstrapped in the test execution. `inventory` is not a downstream dependency of `order` as the former depends on the latter. You basically have two options:

1. If you want to test the whole system end-to-end using scenarios, run the test using `@SpringBootTest` and `@EnableScenarios`. This will bootstrap the entire application and prepare a `Scenario` instance if declared as parameter on the test method.
2. If you'd like to express that you would like to test both the `order` and `inventory` modules in explicit combination, use the `extraIncludes` attribute of `@ApplicationModuleTest` to declare `inventory` to be bootstrapped as well.

**Comment by yossisp** [comment]
Right! I just realized this as well when I took a look at the console output the `Direct module dependencies: none`:
```
2023-06-09T17:38:27.445+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer : # Order
2023-06-09T17:38:27.445+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Logical name: order
2023-06-09T17:38:27.445+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Base package: example.order
2023-06-09T17:38:27.445+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Direct module dependencies: none
2023-06-09T17:38:27.445+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer : > Spring beans:
2023-06-09T17:38:27.446+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer :   + ….OrderManagement
2023-06-09T17:38:27.446+03:00  INFO 998 --- [           main] ustomizerFactory$ModuleContextCustomizer :   o ….internal.OrderInternal
```
Confirming that the test works when adding `@ApplicationModuleTest(extraIncludes = "inventory")`.

I think when using application events such type of test scenario is quite common: a module doesn't have a direct dependency on a downstream module but still wants to test that downstream logic works so I suggest to mention `@SpringBootTest` + `@EnableScenarios` or `extraIncludes` as solutions to allow such tests. I can open a PR to add this to the docs if you want.

**Comment by odrotbohm** [comment]
I would be very happy to review and accept that! 🙃

**Comment by yossisp** [comment]
Ok will do!
