### ISSUE TITLE
Improve documentation of the examples

### ISSUE THREAD

**Issue by nagkumar** [spring-projects/spring-modulith#224]
```
package example;

import example.order.Order;
import example.order.OrderManagement;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Integration test for the overall application.
 *
 * @author Oliver Drotbohm
 */
@SpringBootTest
class ApplicationIntegrationTests
{
    @Autowired
    OrderManagement orders;

    @Test
    void completesOrder() throws Exception
    {
	orders.complete(new Order());
	Thread.sleep(2000);
    }
}

```

and also

```
package example;

import org.junit.jupiter.api.Test;
import org.springframework.modulith.core.ApplicationModules;
import org.springframework.modulith.docs.Documenter;

/**
 * Tests to verify the modular structure and generate documentation for the modules.
 *
 * @author Oliver Drotbohm
 */
class ModularityTests
{
    ApplicationModules modules = ApplicationModules.of(Application.class);

    @Test
    void verifiesModularStructure()
    {
	modules.verify();
    }

    @Test
    void createModuleDocumentation()
    {
	new Documenter(modules).writeDocumentation();
    }
}

```

There are no asserts to make sure test case has done the job perfectly, hence difficult to learn what the code is doing too

The same is the case with all the 3 examples.. surprised, how something can be called as test case without asserting that too in spring like framework
<img width="305" alt="image" src="https://github.com/spring-projects/spring-modulith/assets/332234/c0b9feb3-1ab5-4f5a-8e81-a2aee184adc8">

**Comment by nagkumar** [comment]
Also, kindly say what epr in the example project name is?

Some explanation of each example would help i.e. what each does and how each differ, similar or add-on to other

**Comment by odrotbohm** [comment]
I've added a readme to the [`spring-modulith-examples` folder](https://github.com/spring-projects/spring-modulith/tree/main/spring-modulith-examples).
