### ISSUE TITLE
Core starter should bring `spring-boot-starter`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-modulith#237]
The "core" starter does not bring Spring Boot itself and it should, as described [in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration.custom-starter.starter-module). It looks like other starters may be affected as well.

I don't know enough the project to know for sure but if core represents the "core" feature, then adding it to the other starters is what is the best practice.

**Comment by odrotbohm** [comment]
It definitely pulls in functionality that is activated by auto-configuration.
