### ISSUE TITLE
Support to externalize domain events

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-modulith#248]
It would be nice if externalizing events into messaging middle ware could be supported out of the box by registering an `@ApplicationEventListener` that will forward events to infrastructure like Kafka, AMQP & JMS.

**Comment by olegz** [comment]
May be it is something specific to this project, but in terms of general question the feature of generating and sending messages to  pretty much anywhere (including Kafka, AMQP & JMS) have existed for better part of the decade in [Spring Integration](https://docs.spring.io/spring-integration/docs/current/reference/html/) project

**Comment by denniseffing** [comment]
@odrotbohm I am playing around with the event externalization and I am now wondering how I am supposed to _internalize_ the events (e.g. read them from Kafka and do something) in another Spring Modulith.

Are you planning on adding support for this as well or do you see this as the responsability of the application by e.g. implementing a Kafka consumer manually?
