### ISSUE TITLE
Explicit declaration of `@ApplicationModule(allowedDependencies = {})` should disallow any outgoing dependencies

### ISSUE THREAD

**Issue by marcantoine-bibeau** [spring-projects/spring-modulith#267]
Hi, 

We have a more complex structure where we have a bit more dependency rules. One I figured out is that the developers are currently kinda bypassing modularity rules because they are not configuring the allowedDependencies ApplicationModule annotation.

Long story short, when **not** specifying ApplicationModule.allowedDependencies it's exactly the same as setting ApplicationModule.allowedDependencies = {}

Something I would like and I think that would be more intuitive is to have the following:
**current behavior**
ApplicationModule.allowedDependencies "Not specified" =>  All dependency allowed (current behavior)
ApplicationModule.allowedDependencies = {} => All dependency allowed

**would like**
ApplicationModule.allowedDependencies "Not specified" =>  All dependency allowed (current behavior)
ApplicationModule.allowedDependencies = {} => NO dependency allowed

I understand that this could cause problem for existing system using spring-modulith but a simple configuration could be used to flip the global behavior?

**Comment by odrotbohm** [comment]
> One I figured out is that the developers are currently kinda bypassing modularity rules because they are not configuring the `allowedDependencies` `ApplicationModule` annotation.

Wouldn't that be easy to solve with a custom ArchUnit rule that verifies the attribute being set if the annotation is used? Generally speaking, we could allow enabling a stricter rule, but ultimately, you'd then have to put means in place to make sure that this setting is enabled, wouldn't you?

`@ApplicationModule` is often used to declare a human-readable module name, and trying to do that implying that dependencies would now have to be declared explicitly is mixing concerns.

**Comment by marcantoine-bibeau** [comment]
That is exactly what we are doing right now but intuitively (and maybe my intuition is not that good ;)) what I see a package-info that explicitly defines an empty allowedDependencies, I think that it was intentional to NOT allow anything compare to allow everything.

**Comment by odrotbohm** [comment]
This should be in place now. Would mind giving the snapshots a try ASAP? I'd like to ship an RC2 later today or tomorrow morning, preparing for GA early next week.

**Comment by marcantoine-bibeau** [comment]
Whoa nice :) yes. Give a couple!

**Comment by marcantoine-bibeau** [comment]
Just tried with 0.7.0-SNAPSHOT and it does not work. But 0.7.0-SNAPSHOT does NOT seems to have your changes since ApplicationModule annotation still have 
`String[] allowedDependencies() default {};` 
and not 
`String[] allowedDependencies() default { OPEN_TOKEN };`
![image](https://github.com/spring-projects/spring-modulith/assets/6455702/a35c018b-4c01-4c5c-a069-e2d331831812)

**Comment by odrotbohm** [comment]
Please try `1.0.0-SNAPSHOT`.

**Comment by marcantoine-bibeau** [comment]
I do not see 1.0.0-SNAPSHOT https://repo.spring.io/snapshot...

**Comment by odrotbohm** [comment]
It's here: https://repo.spring.io/ui/native/snapshot/org/springframework/modulith/spring-modulith-core/

Note that 1.0 changes the group id from `….experimental` to `….modulith`.

**Comment by marcantoine-bibeau** [comment]
Perfect, works as it should! Thanks a LOT. Good job for your project! With this I hope we'll be able to build a great structured Monolith ;)
