### ISSUE TITLE
Refactor @Modulith to Compose @SpringBootApplication

### ISSUE THREAD

**Issue by Crain-32** [spring-projects/spring-modulith#282]
Discussed a bit during Spring One, but I'll provide the following justifications as to "why" below.

Lets compare the Inherited Annotations between `@Modulith` and `@SpringBootApplication`

```java
@Documented
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Modulithic
@SpringBootConfiguration
@EnableAutoConfiguration
@ComponentScan(excludeFilters = { //
		@Filter(type = FilterType.CUSTOM, classes = TypeExcludeFilter.class),
		@Filter(type = FilterType.CUSTOM, classes = AutoConfigurationExcludeFilter.class) })
public @interface Modulith { // Assume Aliases }
// Spring Boot
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@SpringBootConfiguration
@EnableAutoConfiguration
@ComponentScan(excludeFilters = { //
		@Filter(type = FilterType.CUSTOM, classes = TypeExcludeFilter.class),
		@Filter(type = FilterType.CUSTOM, classes = AutoConfigurationExcludeFilter.class) })
public @interface SpringBootApplication { // Assume Aliases }
```

You can see that the `@ComponentScan` and `@Configuration` are the same. The main difference being `@SpringBootApplication`'s `@Inherited` (Which I'll admit I don't fully understand) and `@Modulith`'s `@Modulithic`.

I propose (Likely for 1.1.X due to timing) that we Refactor `@Modulith` to be the following.
```java
@Documented
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Modulithic
@SpringBootApplication
public @interface ModulithicSpringApplication { // Assume Aliases }
```
Since the Spring-Modulith Project is supposed to be an opinionated Spring Boot Application, I think the composition of the two Annotations is the best option. It provides a convenient annotation that can easily be used in the baseline of a project, while keeping `@Modulthic` Separate for instances/users who want to use it in specific ways.

**Comment by odrotbohm** [comment]
That's in place now.
