### ISSUE TITLE
Support for open application modules

### ISSUE THREAD

**Issue by Crain-32** [spring-projects/spring-modulith#284]
Last Issue for the Day! I promise.. Probably.... And it'll be a long one, since it's an entire feature request/handling adjustment.

Plugging in Spring One again, but when I attended the [Spring Modulith Deep Dive](https://springone.io/sessions/spring-modulith-a-deep-dive), I realized that although yes, Spring Modulith helps build more Modular Applications, if applied right it allows you to deconstruct Non-Modular Applications. For those with Medium, this [Article ](https://betterprogramming.pub/decoupling-a-core-service-from-your-monolith-the-right-way-ffa6b8e05f5c) is a real-life example of the approach I'm trying to model.

Poor Monolithic Construction has been a long standing pain for many Java Developers. In some cases you'll be locked into Java 8 and Spring Moduliths can't do anything. However with additional handling from `@ApplicationModule` you could begin defining domain boundaries. From my perspective this is a perfect way to take a Monolith, isolate a Domain, enforce that isolation with Spring-Modulith, and then either extract it to a Microservice, or move to the next domain. Likewise it provides extensive Automated Documentation along the way to help keep the Architects/Developers feeling better about the isolation efforts due to the nature of Spring Modulith.

Having better/clearer support for this idea of a "partially" modular project would be a great addition to the Project. I admit I haven't reviewed the automatic Documentation to the point where I feel like this is possible, however as someone who wants to decompose their Monoliths, the following would be *very* nice.

### Adjust `@ApplicationModule` 

If `@ApplicationModule` had a `Boolean enforce() default true;` attribute, it would let partial modules exist in a more comfortable space. I view this in the same way I view TypeScript's [--noImplicitAny](https://www.typescriptlang.org/tsconfig/#noImplicitAny), in that seeing it is a red flag, but some projects are in the state where they need the red flag.

#### Behavior Adjustments
Lets use 3 modules. Assume the full path for `@ApplicationModule`. These modules exist within a larger project.
```java
@ApplicationModule(enforce=true, allowedDependencies = "inventory, package")
package example.order;
// Uses InventoryService and PackageService, Exposes OrderService
```
```java
@ApplicationModule(enforce=false)
package example.inventory;
// Exposes InventoryService
```
```java
@ApplicationModule(enforce=false)
package example.package;
// Exposes PackageService
```
Now lets view the potential results of the following, using the [ApplicationModules Type](https://docs.spring.io/spring-modulith/docs/1.0.0-RC1/reference/html/#fundamentals.modules.application-modules) as a reference
```java
var modules = ApplicationModules.of(Application.class);
modules.forEach(System.out::println);
```
```
## example.order ##
> Logical name: order
> Partial Module: false
> Base package: example.order
> Partial Module Imports: inventory, package
> Spring beans:
  + …OrderService
> Leaky Imports:
  + …InventoryService
  + …PackageService
  
  
## example.inventory ##
> Logical name: inventory
> Partial Module: true
> Base package: example.inventory
> Spring beans:
  + …InventoryService

## example.package##
> Logical name: package
> Partial Module: true
> Base package: example.package
> Spring beans:
  + …PackageService
```
In this case we see that each module now includes the following (Only if at least one "partial" module exists)
- Partial Module: Inverse Mirror of the `enforce` Property in `@ApplicationModule`, it describes that we haven't isolated the entire module's domain, and undefined boundaries might "leak" in through this module.
- Partial Module Imports: Any of the `allowedDependencies` in the `@ApplicationModule` where `enforce` is false.
- Leaky Imports: Any Imported Beans from Partial Modules, which have the ability to "leak" the unmanaged code.

If Order were to be an `allowedDependency` for a new Module, `OrderService` should be considered a Leaky Import, due to `Order` not being a fully Isolated Module when you review the Dependency chain. However it would not show up in `Partial Imports`, as it only has beans declared from other `ApplicationModule`s. 

I'm not sure how to adjust `ApplicationModules.of(Application.class).verify()` to reflect this. But I believe the snippet on the left should fail the test if any "partial" modules are detected, or "leaky" beans. 

To sum this all up. Current Spring Modulith Behavior should not change. Default Behavior should not allow Partial Modules. This is an explicit "opt-in" sort of feature, which is targeted at Users who can't refactor an entire Monolith, but have a need/drive to isolate 1 or more domains.

**Comment by odrotbohm** [comment]
Thanks for writing this up. I have to admit that I am a bit lost in the implementation details (annotation attributes, module model output) but I am not quite sure that I understand the conceptual ideas yet. What is a “partial module”? How far would it behave differently than a not-partial (better term needed?) module?

Are you aware of `ApplicationModuleDetectionStrategy` which allows you to programmatically select application module base packages? It allows you to only return the packages you would want to consider modules. Code living in other packages would not be checked for architectural violations etc.

**Comment by Crain-32** [comment]
@odrotbohm Reading this back I will admit the idea is not clear. My fault for not revisiting it later to see if it still made sense when I wasn't in the midst of it.

I've reviewed the `ApplicationModuleDetectionStrategy`, and it feels like a step towards the idea. The problem is this is less about ignoring/selecting Modules, and more about marking Modules in states of "Purity" or "Cleanliness".

I'll revise the wording by swapping some things around, we'll now have "Clean" Modules, or Modules that have all their dependencies declared and enforced, and "Dirty" Modules, or Modules that might be leaking in other Modules through them, so violations are marked, but not a cause for failure. Not sure what to call modules not enforced by Modulith. Undeclared Modules? Unknown Modules? 🤷🏻‍♂️ 

Now to reuse my example with the Clean/Dirty Wording instead of Partial
> Lets use 3 modules. Assume the full path for @ApplicationModule. These modules exist within a larger project.
```java
@ApplicationModule(clean=true, allowedDependencies = "inventory, package")
package example.order;
// Uses InventoryService and PackageService, Exposes OrderService
@ApplicationModule(clean=false) // clean would be true by default, explicit above for the purpose of the idea.
package example.inventory;
// Exposes InventoryService
@ApplicationModule(clean=false)
package example.package;
// Exposes PackageService
```
> For the output when running ApplicationModules.of(Application.class).forEach(System.out::println);
```
## example.order ##
> Logical name: order
> Clean Module: false  // Maybe skip this if there are no Dirty Modules? since that would be redundant
> Base package: example.order
> Partial Module Imports: inventory, package
> Spring beans:
  + …OrderService
> Dirty Imports:
  + …InventoryService
  + …PackageService
  
  
## example.inventory ##
> Logical name: inventory
> Clean Module: false
> Base package: example.inventory
> Spring beans:
  + …InventoryService

## example.package##
> Logical name: package
> Clean Module: false
> Base package: example.package
> Spring beans:
  + …PackageService
  ```
  We see that the `order` module is `dirty`, because it imports 2 `dirty` modules. Likewise the `inventory` and `package` modules are `dirty` because we explicitly declare them `dirty`. The logic being that if I import a `dirty` module (regardless of how many modules I'm away from it), I'm `dirty`. 
  
  This allows projects to slowly adopt Modulith, while tracking how their `dirty` modules are being imported across the project This solution is better than the `ApplicationModuleDetectionStrategy` because instead of ignoring what packages are not part of the Modulith, you're marking what Modules are not being strictly validated, while also noting their use case. 
  
Hopefully the Clean/Dirty wording is clearer than the "Partial". I believe it's better wording since the idea is figuring out what modules are "tracking mud" around the project.

**Comment by odrotbohm** [comment]
So, now we have attached the clean / dirty labels to modules. What consequences does that have in the context of what Spring Modulith does?

**Comment by DreamStar92** [comment]
@odrotbohm I understand that the intention is to design a mechanism to gradually transform the existing 'big ball of mud' into a more modular structure.Big mud ball is not a public module.

A one-time refactoring migration is not advisable. The big ball of mud is designated as 'dirty.' Qualified modules are cleaned out from the big ball of mud and labeled as 'clean.' During testing, if clean modules leak into dirty modules, they are marked as damaged. If clean modules do not comply with the rules, an error is reported. A topological diagram can be used to show the modularization process in this way.

```
// Test: projdct cleanliness x, no error.
example
└── mudball 肮脏的
    ├── entity
    ├── dao
    ├── service
    └── controller
```
```
// Test: order is damaged because it is affected by mudball. The cleanliness is x and no error is reported.
example
├── order clean
└── mudball dirty
```
```
// Test: order is damaged because it is affected by mudball and inventory . The cleanliness is x and no error is reported.
// The inventory is dirty and violates the xx rules. An error message is reported.
example
├── order clean
├── inventory clean(actually is dirty)
└── catelog dirty
```
```
// order is damaged because it is affected by catelog.
// inventory is clean cleanliness x.
example
├── order clean
├── inventory clean
└── catelog dirty
```
```
// Test project cleanliness 100 Completed the migration of mud balls to modularization
example
├── order clean
├── inventory clean
└── catelog clean
```
The English is translated, please forgive me for the wording.

**Comment by Crain-32** [comment]
@odrotbohm Sorry for taking so long to reply to this.

I spent several weeks stewing over your comment. Obviously in a Project as large as Spring, Features need purposes beyond "This could be useful", as due to the consumer base and influence Spring has. So I wanted to make sure I thought through this a lot before replying.

And then we had a product launch at work and I forgot to reply till now. 🤦🏻‍♂️ 

I believe the only impact I concluded it would have in terms of the consumer of the project is usage of `@ApplicationModuleTest`. Because if there is a Dirty Module, we can't restrict the loading of Modules to have a pure "Vertical" slice, and instead `@ApplicationModuleTest` is basically `@SpringBootTest`. Otherwise as noted above me, it's primarily just a built-in tracking strategy for gradual modularization. Instead of manual tracking with an additional `ApplicationModuleDetectionStrategy`. You could also view it as a `ApplicationModuleDetectionStrategy` that happens to note down what is being ignored within the main Application Classpath. Which doesn't sound 1/2 bad either.

**Comment by odrotbohm** [comment]
Thanks, everyone, for their input on this topic. I have a prototype working here that does the following:

1. Adds an attribute to `@ApplicationModule` to mark a module as _open_
2. Marking a module as _open_ excludes it from checks for cyclic dependencies
3. References to an _open_ module's internals are allowed. Effectively, all types contained in the module become generally accessible for modules not defining allowed targets explicitly. If they list allowed targets, additional references into open modules are still rejected.

Does that match what you were describing above? For 3., do we need an additional flavor that also drops the violations if a module lists explicit dependencies but refers to an open module without declaring it explicitly?
