### ISSUE TITLE
Documentation on event republication behavior misleading

### ISSUE THREAD

**Issue by benjaminknauer** [spring-projects/spring-modulith#288]
I manually threw an exception in an `@ApplicationModuleListener` Method.
There is an event in the `event_publication` table with a null Value in `completion_date`.

So far, so good. But when I restart the application, the event listener is not invoked again. Do I have to configure it somehow? The documentation stats, that the retry should occur by default.

--- 
_Update_

Okay, stupid. You need to enable `spring.modulith.republish-outstanding-events-on-restart` as stated in the documentation appendix. 

Maybe you should consider updating the documentation. In my understanding, setting a property is not "By default, all incomplete event publications are resubmitted at application startup."

**Comment by odrotbohm** [comment]
Good catch! I'm glad you already got to the gist of it. We flipped the default to accommodate multi-instance production deployments, in which a restart of a node might cause unintended side effects. I'll update the reference docs for the next bugfix release.
