### ISSUE TITLE
Remove timezone for the `event_publication` table with Postgres

### ISSUE THREAD

**Issue by patrickuhlmann** [spring-projects/spring-modulith#306]
According to the annex of the [documentation](https://docs.spring.io/spring-modulith/docs/1.1.0-SNAPSHOT/reference/html/#appendix.schemas.postgresql), the publication_date and completion_date are using the type `TIMESTAMP WITH TIME ZONE`

In the [postgres documentation](https://www.postgresql.org/docs/current/datatype-datetime.html) I found the following sentence
`To address these difficulties, we recommend using date/time types that contain both date and time when using time zones. We do not recommend using the type time with time zone (though it is supported by PostgreSQL for legacy applications and for compliance with the SQL standard). PostgreSQL assumes your local time zone for any type containing only date or time.`

In our own projects we have also encountered odd behavior when using with timezone. Maybe it would be fine too for modulith to just use timestamp?

**Comment by odrotbohm** [comment]
Good one, that's fixed.

**Comment by genuss** [comment]
Sorry to interfere, but the `timestamp with timezone` is actually a correct type here. At first, check out this explanation https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29. The postgresql documentation quote is related to `time with timezone` which is a different type:
> ... We do not recommend using the type **time with time zone** ...

A couple of words from me. I think the main issue with these types is bad naming. `timestamp with timezone` is actually a timestamp as we know it, i.e. `Instant` in java, and it doesn't contain any timezone at all. `timestamp` on the other hand is not a timestamp, it's equivalent to `LocalDateTime`.
Consider the following snippet:
```
drop table if exists timestamps;
create temp table timestamps
(
    timestamp_no_tz  timestamp,
    timestamp_wth_tz timestamp with time zone
);
set time zone 'Europe/Berlin';
insert into timestamps (timestamp_no_tz, timestamp_wth_tz)
values ('2020-01-01 10:00', '2020-01-01 10:00'),
       ('2020-01-01 10:00Z', '2020-01-01 10:00Z'),
       ('2020-01-01 10:00[America/New_York]', '2020-01-01 10:00[America/New_York]')
;
select *
from timestamps;
```
I created an [sql fiddle](http://sqlfiddle.com/#!17/5e107/1). As you can see, timestamp without timezone type just ignores time zones set in queries and session. So when different clients with different session time zones insert `timestamp`s into one table, it causes wrong data in database.

So please, revert this change 😄

**Comment by odrotbohm** [comment]
Thanks for chiming in! Great to have some Postgres experts around :). I can certainly revert the change. I don't think we're anticipating application instances using different time zone settings anyway, so the milestone shouldn't cause too much hassle. I've filed #310 to keep track of this.
