### ISSUE TITLE
`@ApplicationModuleTest` loads incorrect slice, if two module names begin with the same string

### ISSUE THREAD

**Issue by MarcoReitano** [spring-projects/spring-modulith#319]
**If two module names begin with the same string (in my case "game"), one ApplicationModuleTest loads an incorrect context slice to test.**
The ApplicationModuleTest for the module "gamemaster" incorrectly spins up the context slice for the module "game", because they start with the same string "game" in package naming.
Renaming one of the module to something like "xgamemaster" or "xgame" fixes the test and correct slice is loaded.
Can't be intended behaviour right? Hope im not missing something here :)

### My package structure
<img width="280" alt="image" src="https://github.com/spring-projects/spring-modulith/assets/5510235/97578a90-458e-4624-a2ef-c8bdb840de7f">

### And my Testresult for the "gamemaster" module
<img width="1535" alt="image" src="https://github.com/spring-projects/spring-modulith/assets/5510235/93727296-dcf0-4eb0-9d39-7e83e5065084">

**Comment by MarcoReitano** [comment]
Some experiments:

- changed modulith version from 1.0.1 to 1.1.0-SNAPSHOT -> issue still there
- logging modules manually in SpringbootTest yields the correct module(names) even if modules begin with the same string
   `var modules = ApplicationModules.of(AmundsenApplication.class).verify();
        modules.forEach(System.out::println);`
    results in: 
   <img width="373" alt="image" src="https://github.com/spring-projects/spring-modulith/assets/5510235/febc510d-f771-4952-ade3-a521d4c91c35">

**Comment by odrotbohm** [comment]
I think we need to revise `ApplicationModules.getModuleForPackage(…)` to filter by exact match or starting with the module's base package and a dot concatenated.

**Comment by odrotbohm** [comment]
Would you mind giving the 1.1 snapshots a try? I'm inclined to back-port the fix to 1.0.x, should it solve your problem.

**Comment by MarcoReitano** [comment]
Hi Oliver,
confirmed - The new snapshot solves the issue!

On a sidenote: 
Thanks for your work with Spring Modulith, im exploring it in my master thesis and it prompted me to (re-)read DDD Redbook. Working with it (in combination with jMolecules) greatly improved my understanding of consistency boundaries, aggregate/module design, domain events, etc.! Something i was always unsure of even in a microservice context, resulting in a dependeny hell / distrubuted big ball of mud in the past! :D

**Comment by odrotbohm** [comment]
Lovely. That’s great to hear. All of it. Wouldn’t mind to have a read on it once you’re done. Always interested in any kind of research in that area and of course happy if I was able to help in any way.
