### ISSUE TITLE
1.1 RC1 Examples does not have the  latest spring boot version 3.2 RC1

### ISSUE THREAD

**Issue by rohanarc** [spring-projects/spring-modulith#338]
[https://github.com/spring-projects/spring-modulith/blob/2241ae19600c57d](https://github.com/spring-projects/spring-modulith/blob/2241ae19600c57d37f60d13da95d2d08f57f07b8/spring-modulith-examples/pom.xml#L7C12-L7C20)

**Comment by odrotbohm** [comment]
Merged pull request against #329.
