### ISSUE TITLE
Publish externalized events to AWS services

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-projects/spring-modulith#344]
In addition to Kafka, AMQP and JMS, Modulith could publish externalized events to AWS services: SQS, SNS and perhaps Kinesis.

This can be implemented either here - using AWS SDK directly - or in [Spring Cloud AWS](https://github.com/awspring/spring-cloud-aws) where we could use Spring Cloud AWS infrastructure to configure AWS clients.

**Comment by odrotbohm** [comment]
That's a great idea! I unfortunately know too little about the AWS APIs. Would you mind taking a look at `KafkaEventExternalizerConfiguration` and how it uses `KafkaOperations` with a `DelegatingEventExternalizer`? If you can point me to a similar infrastructure API that allows sending arbitrary messages to a target and that I can assume gets autoconfigured on a particular classpath arrangement, I'd be happy to add a module that forwards events to that.

**Comment by maciejwalkowiak** [comment]
@odrotbohm I added a PR with SQS and SNS integration. I skipped Kinesis as it has been too long since I've used it and we don't have support for it in Spring Cloud AWS anyway. I am happy to answer any questions :)

**Comment by odrotbohm** [comment]
PR merged, thanks for the contribution!
