### ISSUE TITLE
Unable to publish events: NoSuchMethodError in ApplicationListenerMethodAdapter

### ISSUE THREAD

**Issue by danstooamerican** [spring-projects/spring-modulith#347]
I am using version `1.1.0-SNAPSHOT`. The lastest release breaks our event publishing code.

Whenever we publish an event an exception is thrown:

```
private final ApplicationEventPublisher events;

events.publishEvent(new MyEvent(...));
```

```
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'boolean org.springframework.context.event.ApplicationListenerMethodAdapter.shouldHandle(org.springframework.context.ApplicationEvent)'
```

We migrated to the new version of `@ApplicationModuleListener` in `org.springframework.modulith.events.ApplicationModuleListener`.

**Comment by odrotbohm** [comment]
1.1 RC1 needs Spring Boot 3.1 RC, or better: Spring Framework 6.1 RC1 which introduces the method reported missing.

**Comment by danstooamerican** [comment]
I updated our spring boot dependency to `3.1.0-RC1` but the error persists:

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.1.0-RC1</version>
    <relativePath/>
</parent>
```

**Comment by odrotbohm** [comment]
Please make sure you have Spring Framework 6.1 RC1 on the classpath. That contains the method referred to by the exception.

**Comment by danstooamerican** [comment]
Could you point me to the right dependencies, please?

**Comment by odrotbohm** [comment]
It's the Framework version that Boot 3.2 RC1 pulls in anyway. What versions of Spring Framework libraries does your project list?

**Comment by danstooamerican** [comment]
Updating to `3.2.0-RC1` did the trick.

**Comment by odrotbohm** [comment]
Ah, jeez. Sorry I messed the versions up 🤦🏼‍♂️. So easy to get lost between Boot 3.*2* and Framework 6.*1*. :/

**Comment by danstooamerican** [comment]
No problem, thank you!
