### ISSUE TITLE
Modulith + Native execution gives java.lang.ClassNotFoundException: com.tngtech.archunit.core.importer.ModuleImportPlugin

### ISSUE THREAD

**Issue by silver-mx** [spring-projects/spring-modulith#365]
I created the project available at https://github.com/silver-mx/backup-pcloud-data to experiment with `Java 21 + Spring Modulith + Native compilation` and the execution fails with the following exception (see [native-run.log](https://github.com/spring-projects/spring-modulith/files/13306308/native-run.log)):

```
Caused by: java.lang.ClassNotFoundException: com.tngtech.archunit.core.importer.ModuleImportPlugin
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122) ~[na:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86) ~[na:na]
	at java.base@21/java.lang.Class.forName(DynamicHub.java:1346) ~[backup-pcloud-data:na]
	at java.base@21/java.lang.Class.forName(DynamicHub.java:1309) ~[backup-pcloud-data:na]
	at java.base@21/java.lang.Class.forName(DynamicHub.java:1302) ~[backup-pcloud-data:na]
	at com.tngtech.archunit.core.PluginLoader$PluginSupplier.create(PluginLoader.java:84) ~[na:na]
	... 27 common frames omitted
```

__NOTE:__ Running it from the JAR directly it works fine (see [non-native-run.log](https://github.com/spring-projects/spring-modulith/files/13306313/non-native-run.log)).

### Environment
- OS: `Ubuntu (WSL2-Windows)`
- Java: 
```
java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)
```

### Things I have tried

1. I have tried the native compilation with both gradle and maven by using the Spring's plugin and I get the same issue in both. 
2. I have tried both `implementation 'com.tngtech.archunit:archunit'` and `runtimeOnly 'com.tngtech.archunit:archunit:1.2.0'` to see if it made any difference, but it fails with the same error.

#### Maven

1. Run `git clone https://github.com/silver-mx/backup-pcloud-data.git`
2. Run `./mvnw native:compile -Pnative` to compile in native mode
3. Run `target/backup-pcloud-data`

#### Gradle

1. Run `git clone https://github.com/silver-mx/backup-pcloud-data.git`
2. Run `./gradlew nativeCompile` to compile in native mode
3. Run `build/native/nativeCompile/backup-pcloud-data`

**Comment by odrotbohm** [comment]
Spring Modulith's runtime features (observability etc.) are currently not supported on native images as they require ArchUnit to run, which is currently not GraalVM ready.

**Comment by fpoyer** [comment]
I'm interested in this issue as well : do you guys know if there has been any change since the last comment in the situation ? If not, is there somewhere I could check/follow to be notified if/when this situation changes ?

I'm trying to find the information about ArchUnit not being GraalVM-ready, I'll update this post if I find it.

**Comment by odrotbohm** [comment]
This should work for actuators as of 1.1, thanks to the fix for GH-376.

**Comment by fpoyer** [comment]
Sadly, I reproduced the issue with latest versions... I'm going to open a new issue
