### ISSUE TITLE
Filter passed into `IncompleteEventPublications.resubmitIncompletePublications(…)` has no effect

### ISSUE THREAD

**Issue by benjaminknauer** [spring-projects/spring-modulith#368]
Today I tried to implement some custom routes to resubmit individual outstanding event publications.
I noticed, that the filter in the resubmit function has no effect.

This might fix it: https://github.com/spring-projects/spring-modulith/pull/367

**Comment by odrotbohm** [comment]
Good catch and even better timing. I'll take the PR from here.
