### ISSUE TITLE
`MongoTemplate` warning - `updateFirst` does not support sort

### ISSUE THREAD

**Issue by nkolosnjaji** [spring-projects/spring-modulith#369]
I'm using Mongo Event repository and this warning:

`UpdateFirst does not support sort ('{ "publicationDate" : 1}'); Please use findAndModify() instead`

This warning happens in _MongoDbEventPublicationRepository_ method _markCompleted()_.

- Spring Boot: 3.2.0.RC2
- Spring Modulith: 1.1.0-RC2

I can try submit PR to use _findAndModify()_ instead, what do you think?

**Comment by odrotbohm** [comment]
Sure, appreciated! 👍
