### ISSUE TITLE
Failing asynchronous event handlers do not produce error logs

### ISSUE THREAD

**Issue by benjaminknauer** [spring-projects/spring-modulith#372]
Hello!

I came across this section of code and I think it might benefit from an Error Log here:

https://github.com/spring-projects/spring-modulith/blob/9f42ae43083f2a9e8e19e650a8a5413b183c8087/spring-modulith-events/spring-modulith-events-core/src/main/java/org/springframework/modulith/events/support/CompletionRegisteringAdvisor.java#L176

If this should remain an Info Log, could you please provide some guidance on how to implement a global async exception logging for this? It would be really helpful if this could also be documented, so it's clear for other developers as well.

Thanks a lot!

**Comment by benjaminknauer** [comment]
I think it is also reported in this issue: https://github.com/spring-projects/spring-modulith/issues/311

Registering a custom exception handler also didn't work for me.

**Comment by odrotbohm** [comment]
I've tweaked the advisor to propagate the exception now. This unfortunately has side effects on the republication of synchronous event publications, as they now need to be handled as well. I am currently replicating the behavior of `SimpleAsyncUncaughtExceptionHandler` by logging the exception to the error level. Going forward, I think we can introduce a strategy to allow plug in different ways of handling such exceptions during republications.
