### ISSUE TITLE
ApplicationModuleTest context not reused if inherited config from parent

### ISSUE THREAD

**Issue by JiriFrankCZ** [spring-projects/spring-modulith#382]
### Discussed in https://github.com/spring-projects/spring-modulith/discussions/343

<div type='discussions-op-text'>

<sup>Originally posted by **JiriFrankCZ** October 23, 2023</sup>
Hi all, i´m just wondering whether is correct to bootstrap Spring again and again if we use abstract parent for multiple test with @ApplicationModuleTest. Better explain code:

Base parent class

```
@Transactional
@AutoConfigureMockMvc
@ActiveProfiles("test")
@RecordApplicationEvents
@TestInstance(Lifecycle.PER_CLASS)
@TestClassOrder(ClassOrderer.OrderAnnotation.class)
@TestMethodOrder(OrderAnnotation.class)
@Import({IntegrationTestConfig.class})
@NestedTestConfiguration(EnclosingConfiguration.OVERRIDE)
public abstract class BaseIntegrationTest {
```

Base module class
```
@ApplicationModuleTest(extraIncludes = "config")
public abstract class BaseLightingModuleTest extends BaseIntegrationTest {
    @MockBean
    protected MessageSender messageSender;
    @MockBean
    protected PositionService positionService;
}
```

And real tested class in given module:

```
class PositionEventListenerTest extends BaseShelfModuleTest {
```

I suppose I´m doing something wrong, or this is bad approach, but I found it useful to use it this way. And from my point of view context should be reused, eg. to bootstrap spring context once per module via this abstract parent class. But because of my bad configuration or lack of support in Spring/Modulith, it is currently not easily possible, because conext is bootstraping again and again with every single class like PositionEventListenerTest.

</div>

**Comment by odrotbohm** [comment]
Can you elaborate in which context you'd like to see reuse? `@AMT` will definitely need to create different contexts based on the module the actual test class is located in. It would be helpful to learn more about for which exact scenarios you see the context recreated (classes? if so, in which packages? methods?).

**Comment by odrotbohm** [comment]
Closing this due to the lack of feedback. Feel free to reopen with additional information provided.
