### ISSUE TITLE
Add indexes to `event_publication` tables

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-projects/spring-modulith#403]
Spring Modulith stores published events in `event_publication` table. Schema shipped with Modulith is lacking database indexes, which can result in dramatic performance degradation on the database side - the more events published, the bigger the problem.

While users can (and probably should) implement purging completed events, it may be reasonable to keep them for some period of time for auditing or any other reason. 

Considering that Modulith by default does not purge completed events (#35), I believe it should by default ship database schema that takes it into account and include indexes for queries executed by the framework.

In my particular use case where I use Moduliths with `spring-modulith-starter-jdbc` and PostgreSQL, I added following indexes:

```sql
create index concurrently if not exists event_publication_listener_id_serialized_event_idx on event_publication (listener_id, serialized_event);

create index concurrently if not exists event_publication_completion_date_idx on event_publication (completion_date);
```

**Comment by odrotbohm** [comment]
That's a great idea. Care to craft a pull request?

**Comment by maciejwalkowiak** [comment]
Yes, will take care of it.

**Comment by odrotbohm** [comment]
That's now in place by merging your GH-411. Thanks for the contribution!
