### ISSUE TITLE
`resubmitIncompletePublications` unable to invoke event listeners when using the JDBC event publication registry

### ISSUE THREAD

**Issue by JakeTiritilli** [spring-projects/spring-modulith#409]
We noticed an issue when calling the `PersistentApplicationEventMulticaster.resubmitIncompletePublications` function if using the `spring-modulith-events-jdbc` package instead of `spring-modulith-events-jpa`. The call to `resubmitIncompletePublications` did not cause the incomplete events in the `events_publication` table to be resubmitted to the listeners.

After stepping through the code with the debugger, I noticed that it was [this condition](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/event/ApplicationListenerMethodAdapter.java#L473) in the `getResolvableType` function of the Spring Context `ApplicationListenerMethodAdapter` that was failing (specifically the `!ApplicationEvent.class.isAssignableFrom(declaredEventClass)` part). This resulted in the `resolveArguments` function returning `null`, which in turn caused [this condition](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/event/ApplicationListenerMethodAdapter.java#L236) in the `processEvent` function to be false. Therefore, the `doInvoke` function was never executed.

I'm not familiar with Spring Context internals, so was hoping someone might be able to help me understand what could be causing that to go wrong and why it works correctly when using the JPA registry.

**Comment by dustinsand** [comment]
Comment based off spring-modulith-events-jdbc version 1.1.0.

I think this issue is caused by two different class loaders being used in the call to isAssignableFrom in 
ApplicationListenerMethodAdapter.getResolvableType() 
`(line 457) declaredEventType.isAssignableFrom(payloadType)`

The debugger shows a different class loader for declaredEventType vs payloadType.

JdbcEventPublicationRepository.resultSetToPublication() calls JdbcEventPublicationRepository.loadClass which I think is the culprit.  I'm not 100% certain though, I'm looking into how to modify JdbcEventPublicationRepository.loadClass so the same class loader is used to confirm my theory.

**Comment by odrotbohm** [comment]
Are you using the Spring DevTools by any chance?

**Comment by odrotbohm** [comment]
I was asking because it's actively using a two-class-loader-arrangement for application classes and framework classes (so that the former can be reloaded within a running application). I wonder if this could cause the mismatch in class loaders and thus the failing assignability checks?

**Comment by JakeTiritilli** [comment]
That would make sense, but I actually just tried it again and the problem seems to be resolved now with or without the `spring-boot-devtools` dependency. When I opened this issue, we were using Spring Boot 3.1 and Spring Modulith 1.1.0. To get around it, we switched to using the `spring-modulith-events-jpa` package. Since then, we upgraded to Spring Boot 3.2.1 and Modulith 1.1.1. So now, when I changed the package back to `spring-modulith-events-jdbc`, I noticed that the `resubmitIncompletePublications` function is working as expected.

**Comment by dustinsand** [comment]
I second what @JakeTiritilli posted, I'm not able to reproduce the issue with those versions either.

**Comment by JakeTiritilli** [comment]
Closing the issue because it's not occurring anymore on the latest versions (at the time of writing) of Spring Boot (3.2.1) and Spring Modulith (1.1.1).

**Comment by rodrigoords** [comment]
Hey, I'm having the same issue using spring boot 3.2.1 and Spring Modulith (1.2.1) with spring-modulith-starter-jdbc dependency.

Class is org.springframework.context.event.ApplicationListenerMethodAdapter

Method: ResolvableType getResolvableType(ApplicationEvent event)

Line 473 => `if (!ApplicationEvent.class.isAssignableFrom(eventClass) &&
					payloadType != null && declaredEventType.isAssignableFrom(payloadType)) {
				return declaredEventType;
			}`

declaredEventType.isAssignableFrom(payloadType) always returns false, even though it is the same type.

![Screenshot 2024-08-06 at 14 50 26](https://github.com/user-attachments/assets/37ed9190-a19c-4beb-a97f-13d3bdce130a)
