### ISSUE TITLE
Module can't see its direct dependencies when bean only used in `ConstraintValidator` implementation

### ISSUE THREAD

**Issue by mehmetozanguven** [spring-projects/spring-modulith#418]
> Java 17, Spring boot v3.2.0, spring modulith v1.1.0

Maybe this is the expected behaviour. But let me summarize what happened:

Normally, I don't need to add `@Component` annotation in any of the my custom annotation (spring will automatically inject the corresponding bean) for instance:

- com.mehmetozanguven.myapp.otherDependency => otherDependency module
- com.mehmetozanguven.myapp.auth => auth module (it uses otherDependency.TestService)

Dummy TestService:

```java
package com.mehmetozanguven.myapp.otherDependency;

@Component
@Slf4j
public class TestService {
    // ...
}

```

```java
package com.mehmetozanguven.myapp.auth.validation;

import com.mehmetozanguven.myapp.otherDependency.TestService;

@RequiredArgsConstructor
public class MyCustomValidator implements ConstraintValidator<MyCustomValidation, String> {
   // Spring automatically injects the testService
    private final TestService test;

    @Override
    public boolean isValid(String value, ConstraintValidatorContext context) {
       //...
    }
}
```

However Spring Modulith is failing, which says *No qualifying bean of type ...TestService*, for the Auth-Integration test:

```java
// src/test/java/com/mehmetozanguven/myapp/auth
package com.mehmetozanguven.myapp.auth;

@ApplicationModuleTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        mode = ApplicationModuleTest.BootstrapMode.ALL_DEPENDENCIES)
public class AuthIntegrationTest  {

    @Test
    void dummyTest() {
        
    }
}
```

The solution is to add `@Component` annotation into ConstraintValidator, or inject the TestService(in reality just a dummy injection) any of the bean in the AuthModule:

```java
package com.mehmetozanguven.myapp.auth.validation;

@Component
@RequiredArgsConstructor
public class MyCustomValidator implements ConstraintValidator<MyCustomValidation, String> {
    private final TestService test;
   // ...
}
```

**Comment by odrotbohm** [comment]
Would you mind preparing a small reproducer that shows the problem in a failing test case?

**Comment by mehmetozanguven** [comment]
> Would you mind preparing a small reproducer that shows the problem in a failing test case? Also, from your description it's not clear what exactly is causing the exception. The test case you show dows not have a direct dependency to `TestService`, so I assume some intermediate component is failing to get instantiated? A stack trace would be helpful here.

I have just created simple repo to simulate the issue ([https://github.com/mehmetozanguven/modulith-constraint-validator](https://github.com/mehmetozanguven/modulith-constraint-validator)). You can find the error stack in the readme.md

**Comment by odrotbohm** [comment]
Very helpful. Fix coming in a minute.
