### ISSUE TITLE
Events published from event listener do not trigger listening event listeners

### ISSUE THREAD

**Issue by antechrestos** [spring-projects/spring-modulith#436]
Running spring modulith, I met something telling me I may have not understood something.

Suppose we have three modules:

* The first one publish event (hosted in second module), requesting a treatment. 
* The second module listens (with `TransactionalEventListener`) to the first event, handles it, and publishes a second kind of event to tell the treatment is made
* The third module listens to the late event with `ApplicationModuleListener` 

Everything works well until last part as the third module is not rutriggered: I see the `event_registration` log being populated with the two events, yet the listener of third module is not triggered. 

If I restart application with the `spring.modulith.republish-outstanding-events-on-restart` set to `true`, third module gets triggered..

If the publication of event telling treatment is published from first module (outside event listener), then the third module is triggered.

I made a [demo project](https://github.com/antechrestos/demo-modulith-recursive) with `README.md` and `docker compose` provided.

Thank you.

**Comment by antechrestos** [comment]
After digging, it is a spring issue coupled to a misunderstandig from my part. I solved it by 

* using `EventListener` for synchronous treatment
* using `TransactionnalEventListener` and `ApplicationModuleListener` for treatment to be made at the end of **successfull** treatment of the transaction.

A question remains: as we are receiving an event in a commit phase with `TransactionnalEventListener`, if we publish an other event, listeners who are listening with `TransactionnnalEventListener` should receive the second event if they specify the same phase, shouldn't they?

**Comment by odrotbohm** [comment]
In the second step, do you make sure that the event is triggered from within a transaction? You'd need to either annotate the listener with `@Transactional(propagation = REQUIRES_NEW)` or trigger a service spawning a new transaction. That being easy to miss or get wrong is the reason that `@ApplicationModuleListener` exists in the first place. Any reason you're not using that in step two?
