### ISSUE TITLE
`@ApplicationModuleTest` fails to bootstrap external dependencies

### ISSUE THREAD

**Issue by Kenezke1** [spring-projects/spring-modulith#437]
I have encountered an issue that is only reproducible during testing with @ApplicationModuleTest. The issue comes from the fact that for some reason not all Autowire candidates that are coming from external dependencies will be registered by the test and it will fail to bootstrap and we get the following exception:

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type '[Dependency]' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
`

The issue can be solved if the external packages are added to @Modulithic(additionalPackages=[Dependency]), but this requires the packages to be exposed with @NamedInterface, which might not be possible in all cases. 

Also, noticed that there is no issue with any spring dependencies or Jackson. The issues only came during test run and only with our external dependencies so far.

**Comment by Kenezke1** [comment]
The setup is as follows.

We have a main application for a realistic example let's call it TransactionEngine, this is a Modulithic application with multiple modules. We have another application that functions as a dependency for other projects, e.g. an IpLookup module. This is a completely different project from the previous one. 

The IpLookup project has a service exposed on it called IpLookupService annotated only with @Service. So it's this application that registers the Bean and not the TransactionEngine.

We include this dependency into the TransactionEngine project with maven, then inject the IpLookupService in other services like any other bean.

When I tried to spin up only 1 module of the project, it failed to find the Dependency IpLookupService. I tried all modes on the @ApplicationModuleTest.

I got it working by updating the IpLookupService to have an @NamedInterface on it.

In the TransactionEngine I used @Modulithic(additionalPackages= "org.iplookup")

This made it work for me, but I would expect since the IpLookup module is included with maven, and the modules share maven dependencies across modules since they are a single project, that the IpLookup service is available without any additional changes needed on the library

**Comment by odrotbohm** [comment]
This works as designed. A standard Spring Boot application also only considers types located under the application's base package. Moving away from that approach would mean we'd have to scan *all* dependencies. Furthermore, the default notion of a module is “direct child packages of the application base package”. That convention would fall apart completely. Finally, as you have discovered, a mechanism to include additional packages as root packages already exists.
