### ISSUE TITLE
Postgres index definitions for event registry breaking inserts of publications

### ISSUE THREAD

**Issue by razubuddy** [spring-projects/spring-modulith#519]
Spring Modulith: 1.2.0-M2

After introducing indexes on ENVENT_PUBLICATION table (https://github.com/spring-projects/spring-modulith/issues/403) events with bigger payload are not working due to index size limit.

```sql
INSERT INTO EVENT_PUBLICATION (ID, EVENT_TYPE, LISTENER_ID, PUBLICATION_DATE, SERIALIZED_EVENT)
VALUES (?, ?, ?, ?, ?)
```
raises error
```
ERROR: index row requires 36896 bytes, maximum size is 8191
```

**Comment by odrotbohm** [comment]
If you want to use bigger event payloads, you need to adapt the schema definitions declared [here](https://docs.spring.io/spring-modulith/reference/appendix.html#schemas) to scale up the size of the serialized event column.

**Comment by odrotbohm** [comment]
I am not a Postgres expert, but it looks like we might need to optimize our index declaration. Would you mind adding `USING GIN` to the declaration and try again, as recommended [here](https://www.postgresql.org/docs/current/textsearch-indexes.html)?

**Comment by matiwinnetou** [comment]
Also running into this issue, in my case I can make events smaller but not sure how long this trick will suffice.

**Comment by matiwinnetou** [comment]
@odrotbohm what if one introduces another field, a hash of serialised_event and then put index on it?

**Comment by matiwinnetou** [comment]
Here is my solution, I had to split index into 2:

```
-- Create a GIN index on just the tsvector column
CREATE INDEX IF NOT EXISTS serialized_event_tsvector_idx 
ON event_publication 
USING gin (to_tsvector('simple', serialized_event));

-- Create a separate index for listener_id if needed
CREATE INDEX IF NOT EXISTS listener_id_idx 
ON event_publication 
(listener_id);
```

Unfortunately I could not use JSONB as it is recommended because this is a serialized_event is a TEXT field on JPA in Modulith.

**Comment by JakeTiritilli** [comment]
I'm not sure about other databases, but for PostgreSQL we found that the [hash index](https://hakibenita.com/postgresql-hash-index) works well given that Modulith is doing a full equality comparison on the serialized event instead of searching for a substring. And it's not restricted by the size limit that the b-tree index has. We saw a significant performance improvement in the setting of the completion timestamp after adding this index.
```sql
CREATE INDEX IF NOT EXISTS event_publication_serialized_event_hash_idx ON event_publication USING hash(serialized_event);
```

**Comment by odrotbohm** [comment]
I'll make sure the optimization gets applied in the 1.2 GA release in two weeks and the corresponding service releases for 1.0.x and 1.1.x.

**Comment by dustinsand** [comment]
Hi @odrotbohm, we replaced event_publication_by_listener_id_and_serialized_event_idx with the hash index.

**Comment by odrotbohm** [comment]
Okay, I'll replace the original index for Postgres then. I think I'll refrain from adding additional indexes to make sure we only support the interactions our code triggers. Totally fine if you add more indexes to support interactions you need on top.
