### ISSUE TITLE
spring modulith module emancipation

### ISSUE THREAD

**Issue by sant0s** [spring-projects/spring-modulith#541]
consider a fully decoupled event-publish/subscribe-based https://github.com/odrotbohm/arch-evident-spring/ project. now, let's say that one day the `order` module becomes a microservice of its own. couldn't spring modulith help here? spring modulith knows about inter-module dependencies and, by joining forces with spring initialiser's bootstrap capabilities, it could, for example:

1. generate a new `order` project as a multi-module maven/gradle project with (maven/gradle) modules `order` and `order-api` , this one representing the provided api and therefore including `OrderComplete`
2. update the pom.xml/build.gradle of module `inventory`, which listens to `OrderComplete` events, by adding the `order-api` dependency

what do you think?

```
mvn spring-modulith:emancipate <module>
./gradlew modulithEmancipate <module>
```

**Comment by odrotbohm** [comment]
We're looking into providing support related to this use case in the context of [Spring CLI](https://github.com/spring-projects/spring-cli).
