### ISSUE TITLE
Java 8 date/time type `java.time.Instant` not supported by default

### ISSUE THREAD

**Issue by thestroke82** [spring-projects/spring-modulith#563]
The serializer needs datatype-jsr310.
I apologize in advance if it's already been reported.

**Comment by odrotbohm** [comment]
I am assuming you're referring to the Jackson `ObjectMapper` used to serialize the event instances? That one is picked up from Boot's default setup. The fallback we declare picks up all `Module` beans from the `ApplicationContext`. In other words, if the JSR-310 module is on the classpath it should be registered through Boot.

If that doesn't work, would you mind creating a minimal reproducer for us to investigate?

**Comment by thestroke82** [comment]
Yes I am referring to the Jackson `ObjectMapper`. In fact `jackson-datatype-jsr310` was already present in the classpath, but i still got the error. 
I'll try to reproduce it but really it was no special configuration: some standard Boot starters, js310, `spring-modulith-events-api `and `spring-modulith-starter-jpa`. I get the error when I try to publish an event.

**Comment by odrotbohm** [comment]
You might want to debug into `JacksonEventSerializationConfiguration.jacksonEventSerializer(…)` and see whether the `ObjectProvider` contains a preconfigured instance.

**Comment by odrotbohm** [comment]
Closing as there's not been any development for quite a while.
