### ISSUE TITLE
Property: "spring.modulith.events.jdbc-schema-initialization.enabled" not available/working in springboot 3.2.5

### ISSUE THREAD

**Issue by zikozee** [spring-projects/spring-modulith#582]
![image](https://github.com/spring-projects/spring-modulith/assets/39206162/9be9fce8-c663-4f3d-81b4-7bd660a07054)

Dependencies already added with spring boot initialization

![image](https://github.com/spring-projects/spring-modulith/assets/39206162/581cf49f-c696-483f-a5b6-ad9bcdab1364)

Property not present
![image](https://github.com/spring-projects/spring-modulith/assets/39206162/163e67f7-a0ca-46e1-b5e6-13efa7dff0ab)

**Comment by odrotbohm** [comment]
You're using the JPA module but try to use a property only available for the JDBC implementation.

**Comment by zikozee** [comment]
Thank you for the clarity
![image](https://github.com/spring-projects/spring-modulith/assets/39206162/9be3e76b-5e80-4d28-8a12-e5d5d023f7e1)

I will be closing this
