### ISSUE TITLE
Types residing in packages registered via `@Modulithic(additionalPackages = "…")` not observed

### ISSUE THREAD

**Issue by 9n** [spring-projects/spring-modulith#587]
Provided the following package structure:
```
my-app/
├─ pom.xml
├─ src/
│  ├─ com/example/
│  │  ├─ app/
│  │  │  ├─ Application.java  //annotated with @SpringBootApplication & @Modulithic(additionalPackages = { "com.example.library" })
│  │  │  ├─ moduleA/
│  │  │  ├─ moduleB/
│  │  ├─ library/
│  │  │  ├─ moduleC/
│  │  │  ├─ moduleD/
```
`moduleC` and `moduleD` can't get observed when using `spring-modulith-starter-insight`.

Inspecting the source code, `SpringBootApplicationRuntime.isApplicationClass` considers additional `AutoConfigurationPackages` instead of `@Modulithic.additionalPackages`.  

I can get moduleC and moduleD observed by annotating `Application` class with `@AutoConfigurationPackage(basePackages = "com.example.library")`, but I think this behavior is not intuitive. Is this purposed?

**Comment by odrotbohm** [comment]
Thanks for reporting. That's a great catch. Most certainly a bug.
