### ISSUE TITLE
Create aggregating Asciidoc document including all files generated

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-modulith#638]
We currently generate Asciidoctor snippets for component diagrams of all modules, each module individually and application module canvases. For a global overview, it would be nice if we also generated an aggregating file that includes all snippets in one page.

## Implementation considerations

- File name: `all-docs.adoc`
- We likely have to scan the target folder for files present to make sure we (only) generate imports for all files present, as `Documenter` might be used to render multiple sets of files in different steps.

**Comment by ciberkleid** [comment]
🙋  Working on my own version of this. I will try to figure out how to do it in a way that is contributable.
