### ISSUE TITLE
Add ability to mark a module as OPEN type module without package-info.java

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-projects/spring-modulith#645]
UseCase: Trying to use Spring Modulith for an existing application that uses JOOQ. The JOOQ code generator cleans up existing code and generates new code based on the current DB structure. So, even if I add `package-info.java` by specifying it as an `OPEN` module, the `package-info.java` file gets deleted the next time the code generator runs.

PS: Code from other modules uses various classes from the generated JOOQ code residing in nested packages. I want to mark the entire JOOQ generated code as OPEN module.

Is there a way to configure certain module/package as OPEN type module without `package-info.java` file?

**Comment by lukasdo** [comment]
You can annotate a type residing in the application module's root package with `@ApplicationModule` and therefore mark a module as `OPEN` without a `package-info.java`. See also [Explicit Application Module Dependencies](https://docs.spring.io/spring-modulith/reference/fundamentals.html#modules.explicit-dependencies)

**Comment by sivaprasadreddy** [comment]
I was able to workaround this for JOOQ generated code by placing `package-info.java` at a higher level package.

```
com.mycompany.myapp.jooq
            - package-info.java
             - models
                  - JOOQ code here
```

When JOOQ re-generates code it only deletes `com.mycompany.myapp.jooq.models` sub-directory only, so `package-info.java` remains untouched.
