### ISSUE TITLE
Refactor `ApplicationModules` class to a `interface` to make it extensible

### ISSUE THREAD

**Issue by 9n** [spring-projects/spring-modulith#654]
Current `ApplicationModules` class has `private` constructor, making it hard to be extended and customized.
Why does  `ApplicationModules` a class instead of interface?

related issue: #613

**Comment by odrotbohm** [comment]
`ApplicationModules` is not intended to be extended or customized. The primary reason for this is the caching of `AM` instances created. Can you elaborate on what you're actually trying to achieve?

**Comment by 9n** [comment]
hi @odrotbohm ,  my usage scenario is elaborated in #613.  :)

**Comment by odrotbohm** [comment]
Closing in favor of the support implemented to directly support GH-613.
