### ISSUE TITLE
Module-internal dependencies rejected if allowed dependencies defined explicitly

### ISSUE THREAD

**Issue by mateuszradziszewski** [spring-projects/spring-modulith#660]
Hi, 

I came across issue where verification of application module dependencie fails even though it should not. Consider following example:

Packages structure
```
├── product 
│     ├── package-info.java             <-- Annotated with `@ApplicationModule(allowedDependencies={})`
│     └── repository
│             └── package-info.java     <-- Annotated with `@NamedInterface("repository")`
│             └── Product.java
│             └── ProductRepository.java
├── productmongodb 
│     └── package-info.java             <-- Annotated with `@ApplicationModule(allowedDependencies = {"product::repository"})`
│     └── MongoDbProductRepository.java
└── Application.java                       <-- Annotated with `@SpringBootApplication`
```

`ProductRepository` is interface with instance method `save(Product product)`. 
`MongoDbProductRepository` is concrete class implementing `ProductRepository` interface.

Expected: Verification should pass.
Actual: Verification fails with message "org.springframework.modulith.core.Violations: - Module 'product' depends on named interface(s) 'product :: repository' via com.example.demo.product.repository.ProductRepository -> com.example.demo.product.repository.Product. Allowed targets: none."

Hint:
The reason is that `QualifiedDependency.fromMethodsOf(JavaClass source)` method actually analyzes method `ProductRepository.save(Product product)` for passed argument of `MongoDbProductRepository`.
Exact problematic line of code: [https://github.com/spring-projects/spring-modulith/blob/main/spring-modulith-core/src/main/java/org/springframework/modulith/core/ApplicationModule.java#L1124
](https://github.com/spring-projects/spring-modulith/blob/main/spring-modulith-core/src/main/java/org/springframework/modulith/core/ApplicationModule.java#L1124
)

**Comment by odrotbohm** [comment]
Is there any chance you provide a minimal, complete reproducer? While it's obvious that a module-internal dependency should not be reported as invalid, I still don't quite get which class that's logically assigned to the `product` module is causing the offending dependency.

Am I deducing right, that the processing of `MongoDbProductRepository` (assumingly extending `ProductRepository`?) processes `ProductRepository`, its methods and finds `save(…)` which registers a dependency from `ProductRepository` to `Product`. In `isValidDependency(…)` the check on the declared dependencies then rejects `Product` as it does not consider it to reside in the same module. Correct?

**Comment by odrotbohm** [comment]
Nevermind the reproducer. Got it already.

**Comment by mateuszradziszewski** [comment]
I was about to give you the reproducer :) Your understanding is correct.

**Comment by odrotbohm** [comment]
This should be fixed now. I've also added a backport into 1.2.x via GH-661 and will add further ones for 1.1.x and 1.0.x. Feel free to give the 1.2.1 snapshots a try.

**Comment by mateuszradziszewski** [comment]
I verified that my case works well with version 1.2.1-SNAPSHOT.
