### ISSUE TITLE
Add `spring.modulith.events.jdbc.schema` to allow defining which database schema the `event_publication` table resides in

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-modulith#685]
As described in GH-683, it might be desirable to define the schema for the `event_publication` table explicitly. We could introduce a `spring.modulith.events.jdbc.schema` property to allow easy configuration of that.

## Required steps
- Introduce the property in `src/main/resources/META-INF/spring-configuration-metadata.json`
- Wire the value into `JbcEventPublicationRepository`
- Change the way that the SQL statements are used to augment the table name with the configured schema
- Update documentation accordingly (primarily `src/docs/antora/mopdules/ROOT/pages/appendix.adoc`)
- Optional: introduced Spring Boot configuration properties class `JdbcConfigurationProperties` and use that from the repository implementation. This would allow us to get rid of the manually maintained `spring-configuration-metadata.json` in favor of using the configuration class processor to create the metadata automatically.

**Comment by raedbh** [comment]
What is the expected behavior when configuring the schema property for a MySQL database?

**Comment by odrotbohm** [comment]
Thanks for the contribution. I will have a look at your PR. Assigning you in the meantime so that nobody else accidentally starts working on it.

**Comment by odrotbohm** [comment]
I've applied the PR but actively reject setting the schema for MySQL as it doesn't know about schemas per database. The test for the functionality were flaky and working accidentally if the “no schema configured” ones ran first, as Testcontainers ignores the database name for hostless DB configuration and sets the DB name to `test`. That in turn accidentally matches the allegedly custom schema.

Thanks for the contribution! 🙇

**Comment by raedbh** [comment]
This was exactly the doubtful part I raised in my question above 😅 in MySQL, the 'schema' refers to the database itself..

Thank you for applying the PR and for the feedback.
