### ISSUE TITLE
Reference documentation does not even mention the @Modulith annotation

### ISSUE THREAD

**Issue by Igor-Mukhin** [spring-projects/spring-modulith#689]
There is a `@Modulith` (and `@Modulithic`) annotation in the library. The documentation about how and when to use it is missing from the reference documentation: https://docs.spring.io/spring-modulith/docs/current-SNAPSHOT/reference/html/

Additional topics that are missing from the reference documentation:

- How can you group some modules in a subpackage? i.e. app.moduleA, app.moduleB, app.group1.moduleC, app.group2.moduleD (If you have a significant number of modules, you will probably need it)
- Can you have a module like "config" that is unrestricted in what classes it may access?

**Comment by odrotbohm** [comment]
Where did you find that particular link? The current reference documentation resides [here](https://docs.spring.io/spring-modulith/reference/). The `@Modulithic` annotation (which `@Modulith` is just an extension of) is documented [here](https://docs.spring.io/spring-modulith/reference/fundamentals.html#customizing-modules-arrangement).

Note that the reference documentation cannot give general purpose module design advice (your second point). Your first point is currently not supported as such, and I think you can understand that it's hard to document all the things that are not supported yet. The [section](https://docs.spring.io/spring-modulith/reference/fundamentals.html#customizing-modules) on how to customize the module detection might be helpful, though.

**Comment by odrotbohm** [comment]
Thanks, I'll report that to the docs team to see how we can improve the search engines better picking up the new location.
