### ISSUE TITLE
The generated documentation Modules Canvases do not contain Types implemented in the nested packages.

### ISSUE THREAD

**Issue by PostIt59** [spring-projects/spring-modulith#724]
First of all, thank you @odrotbohm for the tremendous work you've done over the years on the jMolecules and Spring Modulith projects!

Based on this repository: https://github.com/odrotbohm/tactical-ddd-workshop/tree/main/04-moduliths, the types are present in the generated modules canvas files.

However, if I decide to create nested packages (e.g. `domain/`) and put classes annotated as `AggregateRoot`, `Entity`, `ValueObject` etc. there, then the types are not present in the modules canvas files.

I wanted to know if this is a bug, a planned feature, or if there's simply another reason ?

Thank for your help

**Comment by odrotbohm** [comment]
This is a feature. By default, the Application Module Canvas describes the API of a module, i.e. only architectural elements that are visible to other modules. The idea is that the documentation is usually most interesting to *other* module's developers. To those, it would be puzzling, if the canvas contained elements that they, then, cannot refer to without introducing an architectural violation.

That said, `CanvasOptions` exposes a `revealInternals()` that would disable the visibility check and the canvas would contain the types hidden inside the module as well.
