### ISSUE TITLE
Modulith-actuator + Native = ClassNotFoundException: com.tngtech.archunit.core.importer.ModuleImportPlugin

### ISSUE THREAD

**Issue by fpoyer** [spring-projects/spring-modulith#735]
Following advice from @odrotbohm in https://github.com/spring-projects/spring-modulith/issues/365 I tried to create a minimalist example of spring native + spring modulith with actuators, using latest versions available from https://start/spring.io, but I got the same error.

What I did : create new project from https://start.spring.io , with
-  latest Spring Boot (3.3.1), 
- Maven, 
- JAR, 
- Java 21, 
- dependencies on native, modulith and actuator, 

resulting in the project visible here : https://github.com/fpoyer/spring-modulith-native-actuator

What I expected : to be able to compile a native image and run it with no error

What I got : error on startup ending with
```
Caused by: java.lang.ClassNotFoundException: com.tngtech.archunit.core.importer.ModuleImportPlugin
```
What I tried : 
- changing dependency from spring-modulith-observability to spring-modulith-insight => same result
- removing dependencies to spring-modulith-observability and spring-modulith-insight => application starts as expected, but no modulith actuator (obviously)

Am I missing something obvious or is spring-modulith-actuator still not compatible with native image compilation ?

**Comment by odrotbohm** [comment]
I unfortunately cannot get the reproducer to run as the build fails with:

```
[INFO]     [creator]     #
[INFO]     [creator]     # A fatal error has been detected by the Java Runtime Environment:
[INFO]     [creator]     [thread 258 also had an error][thread 256 also had an error]#
[INFO]     [creator]     #  
[INFO]     [creator]     
[INFO]     [creator]     SIGSEGV (0xb) at pc=0x00007ffffe939ac5, pid=224, tid=257
[INFO]     [creator]     #
[INFO]     [creator]     # JRE version: OpenJDK Runtime Environment Liberica-NIK-23.1.3-2 (21.0.3+10) (build 21.0.3+10-LTS)
[INFO]     [creator]     # Java VM: OpenJDK 64-Bit Server VM Liberica-NIK-23.1.3-2 (21.0.3+10-LTS, mixed mode, tiered, jvmci, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
[INFO]     [creator]     # Problematic frame:
[INFO]     [creator]     # V  [libjvm.so+0xf39ac5][thread 253 also had an error]
[INFO]     [creator]       ObjectSynchronizer::quick_enter(oopDesc*, JavaThread*, BasicLock*)+0x15
[INFO]     [creator]     #
[INFO]     [creator]     # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[INFO]     [creator]     #
[INFO]     [creator]     # An error report file with more information is saved as:
[INFO]     [creator]     # /layers/paketo-buildpacks_native-image/native-image/hs_err_pid224.log
[INFO]     [creator]     [thread 252 also had an error]
[INFO]     [creator]     [2.900s][warning][os] Loading hsdis library failed
[INFO]     [creator]     #
[INFO]     [creator]     # If you would like to submit a bug report, please visit:
[INFO]     [creator]     #   https://bell-sw.com/support
[INFO]     [creator]     #
[INFO]     [creator]     Error: Image build request for 'com.example.spring_native_actuator.SpringNativeActuatorApplication' (pid: 224, path: /layers/paketo-buildpacks_native-image/native-image) failed with exit status 134
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 134
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] ------------------------------------------------------------------------
```

That looks like a buildpacks issue, though. What I can see though, is that the architectural description is generated for inclusion in the image:

```
[INFO] --- spring-boot:3.3.1:process-aot (process-aot) @ spring-native-actuator ---
…
… c.e.s.SpringNativeActuatorApplication    : Starting SpringNativeActuatorApplication using Java 21.0.3 with PID 97936 (/Users/odrotbohm/temp/spring-modulith-native-actuator/target/classes started by odrotbohm in /Users/odrotbohm/temp/spring-modulith-native-actuator)
… c.e.s.SpringNativeActuatorApplication    : No active profile set, falling back to 1 default profile: "default"
… com.tngtech.archunit.core.PluginLoader   : Detected Java version 21.0.3
… onfiguration$ApplicationModulesBootstrap : No application modules detected!
… pplicationModulesFileGeneratingProcessor : Generating application modules information to META-INF/spring-modulith/application-modules.json
```

Also, the example includes the currently unsupported `observability` JAR (via the insight starter). If you flip that to only include the `spring-modulith-actuator` and run `./mvnw -Pnative clean native:compile` you'll get an artifact that starts successfully.

**Comment by odrotbohm** [comment]
The failing buildpacks build seems to be related to being in an M1 Mac. I.e., you should see your project build when flipping the dependency to only include the actuator one.

**Comment by fpoyer** [comment]
spring-modulith-observability seems is the problem indeed, removing it from the classpath (by changing spring-modulith-starter-insight to spring-modulith-actuator solves the situation.

Thanks for your help !
