### ISSUE TITLE
`JpaEventPublication` class's serializedEvent field is too short to save Huge Size json value

### ISSUE THREAD

**Issue by tlarbals824** [spring-projects/spring-modulith#759]
when using `ApplicationModuleListener` with mysql,   I encountered an error message "Data truncation: Data too long for column 'serialized_event' at row 1"

i found that `JpaEventPublication`'s serializedEvent field is type of String and the default JPA mapping for String in RDBMS is varchar(255).

Then how about changing the serializedEvent field type to Text instead of varchar(255)?

**Comment by odrotbohm** [comment]
We do not control the size of the column of your database. You'll have to make sure you set up your schema in a way that it can capture the events your code is handling.
