### ISSUE TITLE
`ApplicationModules.of(…)` throws `NoClassDefFoundError` when using the jMolecules Kotlin library

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-modulith#801]
I'm trying out Spring Modulith 1.2.3 with a Spring Boot 3.3.3 project that is written in Kotlin. On the [Verifying Application Module Structure](https://docs.spring.io/spring-modulith/reference/verification.html) page I read about jMolecules, and I found that `jmolecules-ddd` has a Kotlin counterpart called [kmolecules-ddd](https://github.com/xmolecules/jmolecules?tab=readme-ov-file#available-libraries).

However, after adding `org.jmolecules:kmolecules-ddd` to my project, I got `java.lang.NoClassDefFoundError: org/jmolecules/ddd/annotation/Module` when calling `org.springframework.modulith.core.ApplicationModuleInformation#of` for Spring Modulith application module verification and documentation generation.

This seems to happen because `JMoleculesTypes.isPresent()` returns `true`, because `org.jmolecules.ddd.annotation.Entity` is present (provided by `kmolecules-ddd`), but `JMoleculesModule.supports(lookup)` then tries to look up `org.jmolecules.ddd.annotation.Module`, which is not provided by `kmolecules-ddd` (although it is indeed provided by `jmolecules-ddd`).

**Comment by breun** [comment]
`@BoundedContext` and `@Module` were added to `jmolecules-ddd` via https://github.com/xmolecules/jmolecules/issues/20, but weren't added to `kmolecules-ddd`. I've created https://github.com/xmolecules/jmolecules/issues/126 for this.

**Comment by breun** [comment]
I'm now thinking that these annotations are probably missing from `kmolecules-ddd`, because these are package-level annotations and Kotlin doesn't provide a way to define package-level annotations.

Maybe it's then best to let Spring Modulith not fail when `org.jmolecules.ddd.annotation.Module` is not present?

**Comment by odrotbohm** [comment]
An improve guard should be in place. Feel free to give the snapshots a try!

**Comment by breun** [comment]
Great, thx! Can this fix be backported to 1.2.x as well? (And maybe 1.1.x if that's affected too and still maintained, but personally use 1.2.x.)
