### ISSUE TITLE
Add archiving event publication completion mode

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-modulith#806]
The recently introduced [delete completion mode](GH-748) provides an alternative to the default updating mode. It allows keeping the number of event publication entries low at the expense of completed publications not being accessible. A new archiving mode could augment the deletion of the original entry with an insert into a publication archive.

## Required steps
* Augment `CompletionMode` enum with `ARCHIVING` value
* In JDBC, Add schema files that create a separate database table. Adapt SQL statement creation to let the completion and the lookup of completed publications target that new archive table.
* Similar approaches for MongoDB, Neo4j and JPA

**Comment by cmetzlerhg** [comment]
This actually seems to me like a breaking change for those who run Flyway to apply database migrations. Maybe worth to mention in the release notes.

**Comment by odrotbohm** [comment]
This is not a breaking change as it requires opting into the mode explicitly.

**Comment by odrotbohm** [comment]
Please open a new ticket with more details on what exactly broke. I have a hunch it's unrelated to this particular addition but we certainly have to fix that.

**Comment by cmetzlerhg** [comment]
Just updated my comment, I think that's the root cause.

**Comment by odrotbohm** [comment]
This ticket has been closed against an already released version. As indicated above, to follow up, we need a new ticket and more details about what you see, what you expect. Ideally in a minimal reproducer.
