### ISSUE TITLE
Release 1.2.4

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-modulith#811]

**Comment by davidkarlsen** [comment]
Will this include #804 ?

**Comment by odrotbohm** [comment]
Nope. As indicated in the fix version of the other ticket, I've merged this for 1.3 only as we generally only add new features in minor versions for stability reasons. We're going to ship the RC next week, i.e. it's close to being available in GA form.

Any particular reason you hoped to see it in 1.2?

**Comment by davidkarlsen** [comment]
@odrotbohm yeah - I noticed in the milestones after asking - do you publish RCs/milestones anywhere? I just want an external final build if possible.

**Comment by odrotbohm** [comment]
Yes, current snapshots can be found by referring to `1.3.0-SNAPSHOT` and https://repo.spring.io/snapshot *today*. On release date (next Friday), `1.3.0-RC1` will be available from http://repo.spring.io/milestone.
