### ISSUE TITLE
Rename `FormatableType` to `FormattableType`

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-modulith#813]
I'm not a native English speaker, but I believe that if something can be formatted, then it is 'formattable' rather than 'formatable', so I believe the class name `FormatableType` should be renamed to `FormattableType`.

**Comment by odrotbohm** [comment]
Good catch! Unfortunately, I think this will have to wait until 2.0 as it's a public type and fixing the typo will break existing clients.

**Comment by breun** [comment]
Maybe `FormattableType` can already be introduced before 2.0 next to `Formatabletype` by letting `FormattableType` extend `FormatableType` and marking `FormatableType` as deprecated for removal in 2.0?

Then Spring Modulith itself could already switch to `FormattableType` and existing users can also already switch before 2.0 if they want.
