### ISSUE TITLE
Reference documentation missing generated images

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-modulith#843]
![Screenshot from 2024-09-24 12-49-30](https://github.com/user-attachments/assets/f5b4de4f-d7b4-4414-b12a-e88a69facd4f)

**Comment by xenoterracide** [comment]
![Screenshot from 2024-09-24 13-02-26](https://github.com/user-attachments/assets/09d02b1b-1752-4fb5-b19c-830b71877bc6)

**Comment by Rejish07** [comment]
hi, I am Rejish. I am begginner in open source contribution and i need someone to help me for learn how this open contribution happens, if someone is willing to give me a support i am open for that,
contact : rejishmahi@gmail.com
