### ISSUE TITLE
Integration testing section missing mentioning the artifacts that are needed

### ISSUE THREAD

**Issue by murdos** [spring-projects/spring-modulith#850]
https://docs.spring.io/spring-modulith/reference/testing.html is missing the indication that dependency `spring-modulith-starter-test` should be added.

In the [Overview](https://docs.spring.io/spring-modulith/reference/index.html), it is said that "The individual sections describing Spring Modulith features will refer to the individual artifacts that are needed to make use of the feature."
It's true for most sections, but not this one.

**Comment by odrotbohm** [comment]
Good catch, thanks for reporting! 🙇
