### ISSUE TITLE
Provide NamedInterfaces and shared modules lookup strategies

### ISSUE THREAD

**Issue by murdos** [spring-projects/spring-modulith#851]
While trying to setup spring-modulith on an existing project that has already multiple modules, each one designed to used hexagonal architecture, I realized that spring-modulith does not support hexagonal architecture.

I think that by allowing spring-modulith modules detection to be more customizable, by providing additional extension points like strategies for identifying NamedInterfaces from a module base package, it should be possible to support this architecture, and others.

I made a rough experiment here:
- [spring-modulith changes](https://github.com/murdos/spring-modulith/commit/d778c8820bbb489d31ea9491cc1e4f9a4e7a2289)
- [the hexagonal-project](https://github.com/murdos/jhipster-lite/commit/5d60be0c9f2107833122800e330a7754db827725#diff-f46433ef22eefdb21fc1048c6af19ac70a9d3b43d5a4446087610b8f38200e6c)

Note that it would require to open API to create NamedInterfaces and NamedInterface.

Additionally, it would probably be useful to provide a lookup strategy to identify shared modules, when it's possible to automatically detect them, and avoid manual declarations through `@Modulithic` attribute.

**Comment by odrotbohm** [comment]
Thanks for opening up this ticket. I think before jumping to conclusions (Spring Modulith not supporting hexagonal architecture) and suggesting changes to the implementation, it would be helpful if you laid out what you're trying to achieve, what means you're using to implement those goals. We can then elaborate whether those are the appropriate ones or whether there are alternative approaches.

Fundamentally, any of the separation of concerns architectures (Hexagonal, Onion) are an implementation detail to a module. With [jMolecules](https://github.com/xmolecules/jmolecules?tab=readme-ov-file#use-case-expressing-architectural-concepts), a library exists that allows declaring the architectural stereotypes language in the codebase. In combination with Spring Modulith's named interface concept, we know about several applications using Hexagonal Architecture and Spring Modulith in combination.

Any chance you provide a minimal reproducer to demonstrate what you're looking for? I cannot really tell that from the sample project you linked to. Ideally without any references to third-party frameworks that might already come with precompile opinions? The last time I interacted with JHipster, the team was pretty opposed to a domain-oriented code arrangement approach, insisted on a rather technical first-level decomposition strategy, which is at odds with decomposion for encapsulation.

**Comment by odrotbohm** [comment]
Closing due to the lack of feedback. Feel free to reopen with further information
