### ISSUE TITLE
Run maven tests on PRs

### ISSUE THREAD

**Issue by nkolosnjaji** [spring-projects/spring-modulith#86]
Github runs maven test on each PR

**Comment by odrotbohm** [comment]
They seem to wait for approval by a team member (I guess for security reasons). Did you want to express the simple test runs should simply be executed? Or shall we rather exclude PRs from triggering the build?

**Comment by nkolosnjaji** [comment]
I thought that Github will not run test on PR and developers/mainterners will not have feedback, but that's not the case so I think this issue is invalid and can be closed.

**Comment by codespearhead** [comment]
@nkolosnjaji Can you [close this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue) then?
