### ISSUE TITLE
documentation: offer advice on Identitifier location

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-modulith#867]
Prelude: Spring Modulith is very opinionated about the structure of your code and ensuring you have no circular dependencies. Presumption, you're using DDD statically typed Id's, e.g `UserId` not `UUID` is exposed. Obviously if the type were simply `Long` or `UUID` this question wouldn't matter at all.

Question that documentation should answer (IMHO). Where should `UserId` live? in the package with User? making all of the modules that relate to User depend on the "modulith module" user lives in? should you put these identifiers in a common module that everything can safely depend on? should a module make its own opaque copy of `UserId` like it would probably have to if it was referencing a 3rd party system? or are we trying to enforce that a that relationship can only be unidirectional.

**Comment by odrotbohm** [comment]
Spring Modulith does not have an opinion about how you design your domain types. Furthermore, a reference documentation is not the right place to give general design advice. The question you raise are of common design nature and are in no means specific to Spring Modulith.

**Comment by xenoterracide** [comment]
You do obviously have a strong opinion on where you put those types though. Which means you have a strong opinion on package structure. You equate packages to modules. Therefore you have to have an opinion on whether an aggregate identity lives in the same module as the aggregate. But you can say it doesn't that's fine.
