### ISSUE TITLE
Add `LICENSE` and `NOTICE` to binary distribution

### ISSUE THREAD

**Issue by b-abel** [spring-projects/spring-modulith#874]
The license file does not contain the Copyright owner (and years). It only contains the placeholder `Copyright [yyyy] [name of copyright owner]`. This causes compliance check tools (e.g. https://www.mend.io) to fail.

**Comment by odrotbohm** [comment]
I see Framework, Boot and Security use a slightly different placeholder (`Copyright {yyyy} {name of copyright owner}`). Does the tool bark on that as well? I'm unsure about the request in general, as even [projects](https://github.com/apache/camel/blob/main/LICENSE.txt) of the Apache foundation itself use these placeholders? Maybe it's rather something to report to the tool vendor?

**Comment by b-abel** [comment]
Hi @odrotbohm , thank you for looking at the issue. It is not clear to me how the tool acquires its information. For Spring Boot it contains copyright information and references the file https://github.com/spring-projects/spring-boot/blob/fadd05412e0c16493430978a72ca2f44b232d68f/buildSrc/src/main/resources/NOTICE.txt 
But this is a completely different approach to checking the license file. There is different information for the Spring framework. It looks like the data was entered manually. 
I'm not sure how to proceed with this. On the one hand, my naive understanding of the Apache 2.0 license template is that the copyright should be added to the license file. On the other hand, I see that no one seems to be doing this.

**Comment by odrotbohm** [comment]
I am assuming the scanner is rather looking at the binaries included in your project, and we don't ship `LICENSE` and `NOTICE` with those. How quickly could you provide feedback on this? I'm going to add the files, and they'll be available in the 1.3 snapshots shortly.

**Comment by b-abel** [comment]
Thank you for your resolution. I can only try it in an enterprise environment where it is difficult to use snapshots. I can check it once it is on Maven Central.
