### ISSUE TITLE
The method annotated with `ApplicationModuleListener` is not triggered when the event is published

### ISSUE THREAD

**Issue by piotrooo** [spring-projects/spring-modulith#915]
Let's consider the following sample.

Module: `incoming.service`

```java
package incoming.service;

@Service
public class IncomingMessageHandler {
    @ApplicationModuleListener
    public void handle(IncomingMessageReceivedTO incomingMessageReceivedTO) {
        // do db and other things
    }
}
```

Module: `provider.incoming.rest`

```java
package provider.incoming.rest;

@RestController
class ProviderIncomingMessagesPublicController {
    private final ApplicationEventPublisher applicationEventPublisher;

    ProviderIncomingMessagesPublicController(ApplicationEventPublisher applicationEventPublisher) {
        this.applicationEventPublisher =
                requireNonNull(applicationEventPublisher, "applicationEventPublisher cannot be null");
    }

    @PostMapping("/public/provider/incoming-messages")
    @ResponseStatus(OK)
    @Transactional // <-- This is required for trigger 
    String handleIncomingMessage(@RequestBody ProviderIncomingMessageRequest providerIncomingMessageRequest) {
        IncomingMessageReceivedTO incomingMessageReceivedTO = toIncomingMessageCallback(providerIncomingMessageRequest);
        applicationEventPublisher.publishEvent(incomingMessageReceivedTO);
        return OK_RESPONSE;
    }
}
```

For both the `org.springframework.modulith:spring-modulith-starter-jpa` and `org.springframework.modulith:spring-modulith-starter-jdbc` starters, I need to add a `@Transactional` annotation to a method that doesn't interact with the database. It feels a bit non-intuitive.

Is it a bug or a feature? :wink:

**Comment by odrotbohm** [comment]
Yes, see the [reference documentation](https://docs.spring.io/spring-modulith/reference/events.html) for details.

**Comment by nilshartmann** [comment]
Hi @odrotbohm ,

sorry for coming back to this old issue, but out of curiosity: what is the reason that application events are delivered by the publication registry only when published from inside a transaction? Given the example above, wouldn't it make sense to have the benefits of the publication registry (republishing etc) even when the event is not published inside a transactional method? 

If I see it correctly the events are stored in the `event_publication` table anyway (even when published outside transaction), and they also are delivered (and marked as completed) when annotating a handler method with:
```java
    @Async
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    @TransactionalEventListener(fallbackExecution = true) // <---
    //  instead of:   @ApplicationModuleListener 

```

**Comment by odrotbohm** [comment]
The delivery is not performed by the EPR but Spring's ApplicationEventMulticaster. The reason for the default behavior is that secondary functionality is usually dependent on the result of some primary unit of work and must only be executed *after* that unit of work has completed. Especially if it's running in a transaction itself, it needs to be able to see the result of the primary functionality.

Setting `fallbackExecution` to `true` causes the listener to be invoked immediately if no transaction is running, potentially not seeing related state changes of the primary functionality. I.e., without a transaction, whether a listener sees the correct data is dependent on the event publication in relation to the primary state changes. Especially with aggregate persistence, a change on such an aggregate typically results in multiple database interactions.

Attaching the secondary functionality to a primary transaction is also necessary, as—in your example—the primary functionality would conclude *after* the listener has been invoked and could result in a failure of that primary functionality. The direct invocation of the listener would now mark the publication as resolved, but the system might end up in an inconsistent state. I'll talk about this stuff a lot in [this presentation](https://www.youtube.com/watch?v=eiFnSevxAdk).

**Comment by nilshartmann** [comment]
Hi @odrotbohm ,

thanks for your explanation. I  totally agree with publishing events after a completed unit of work (for me `@TransactionalEventListener` is one of the most underrated Spring features even without Spring Modulith).  

But what I had in mind when asking my question was in a slightly different direction. Wouldn't it be possible to _also_ support the use-case where we have no transaction at all in the primary "functionality"? Let's think of external events received via HTTP in a RestController (for example events published by the GitHub Webhook API). To make sure I don't loose any of those events in case of application or infrastructure problems, I could store them in a DB (or message broker, ...) and implement some retry mechanism. And at this point I wonder if it wouldn't be possible to (mis)use the EPR, because that already does this exact thing. (In some way "internalizing" events into our application vs externalizing them with `@Externalized`.)
