### ISSUE TITLE
Controllers implementing interfaces not mapped when the observability module is used

### ISSUE THREAD

**Issue by anguzo** [spring-projects/spring-modulith#933]
### Description
When using Interface-Driven Controllers in a Spring project configured with `spring-web`, `spring-modulith`, and `spring-boot-actuator`, the controllers do not function as expected. The issue appears specifically when including `spring-modulith-observability` as a runtime dependency.

For example, the following setup fails to work:

```kotlin
@RestController
class HelloController : HelloResource {
    override fun hello(testText: String): String {
        return testText
    }
}

interface HelloResource {
    @GetMapping("/api/hello")
    fun hello(@RequestParam("testText") testText: String): String
}
```

### Reproducing the Issue
Here is a minimal sample to reproduce the issue:
[demo.zip](https://github.com/user-attachments/files/17747357/demo.zip)

When adding `runtimeOnly("org.springframework.modulith:spring-modulith-observability")` in the Gradle configuration, Interface-Driven Controllers fail to function. Removing this dependency allows the controllers to work as expected.

### Expected Behavior

The application should process requests to the `/api/hello` endpoint and return the provided `testText` parameter as expected.

### Observed Behavior
When `spring-modulith-observability` is included as a dependency, the endpoint does not work.

**Comment by anguzo** [comment]
I will also include Java/Maven based minimal sample, the problem persists in it as well.
[demo_java.zip](https://github.com/user-attachments/files/17747457/demo_java.zip)

**Comment by odrotbohm** [comment]
We now consider the global AOP proxying settings when applying the observability decoration. Please give the 1.4 snapshots a try!

**Comment by anguzo** [comment]
Thank you, tried 1.4.0-SNAPSHOT and the issue is indeed resolved.

**Comment by odrotbohm** [comment]
Thanks for the feedback and happy coding! 🙌
