### ISSUE TITLE
Add ability to use Awaitility to retry assertion N times after an event is published using Scenario API

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-projects/spring-modulith#948]
**UseCase:** Publish an event which should be handled by an event listener and add/update a row in DB. The listener won't publish any events.

```java
var event = new OrderCreatedEvent(orderId, productCode, 2);
        scenario.publish(event)
                .andWaitForStateChange(() -> inventoryService.getStockLevel(productCode))
                .andVerify(stockLevel -> assertThat(stockLevel).isEqualTo(598));
```

But this test is non-deterministic and flaky. 

The current implementation calls `inventoryService.getStockLevel(productCode)` only once and trying to assert which is failing based on whether the DB changes are already committed or not.

Sometimes the event handler logic may take time, and we may need to retry calling `inventoryService.getStockLevel(productCode)` N times waiting for at most X seconds.

As a workaround, I am using Awaitility as follows (not ideal usage of `andWaitForStateChange()`):

```java
scenario.publish(event)
                .andWaitForStateChange(() -> productCode)
                .andVerify(code -> Awaitility.await()
                        .atMost(Duration.ofSeconds(10))
                        .pollInterval(Duration.ofSeconds(2))
                        .untilAsserted(() -> {
                            Long stockLevel = inventoryService.getStockLevel(code);
                            assertThat(stockLevel).isEqualTo(598);
                        }));
```

Request: Please add the ability to verify the state change by calling a supplier N times and asserting the result.

**Comment by odrotbohm** [comment]
> The current implementation calls `inventoryService.getStockLevel(productCode)` only once and trying to assert which is failing based on whether the DB changes are already committed or not.

That's correct, but only due to the default of `….andWaitForStateChange(…)` defaulting to consider any non-`null` value to signal a successful state change. Couldn't you simply rather use `inventoryService.getStockLevel(productCode) == 598` to let the `Scenario` to wait for that condition to be met?

**Comment by sivaprasadreddy** [comment]
That worked as expected.

```
scenario.publish(event).andWaitForStateChange(() -> inventoryService.getStockLevel(productCode) == 598);
```
Thanks a lot for quick response @odrotbohm .
