### ISSUE TITLE
Provide a Spring Boot compatibility matrix

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-modulith#971]
It would be nice if users could easily determine which Spring Modulith version should be used for a project using a particular version of Spring Boot.

By manually inspecting dependencies I've found the following:

| Spring Boot | Spring Modulith |
| ----------- | --------------- |
| 3.4.x       | 1.3.x           |
| 3.3.x       | 1.2.x           |
| 3.2.x       | 1.1.x           |

It might be nice to have this as part of the documentation and/or readme?

**Comment by odrotbohm** [comment]
Do you think you could prepare a PR for the docs to add that. Generally speaking, there shouldn't be much need for this actually, as as of right now, every maintained Spring Modulith version should work with every OS-maintained Boot version greater than 3.0.

**Comment by breun** [comment]
I didn't know that, but if that's true, then it would be good if that fact was documented somewhere. But I guess users would like a bit more certainty than 'it should work'.

I'm not sure what compatibility guarantees Spring Modulith can currently give, and therefore also not sure what could be stated in the documentation about this.

**Comment by odrotbohm** [comment]
That's in place now and also backported to 1.3, 1.2, and 1.1.
